[package]
name = "crabgresql-catalog"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crabgresql-storage-api.workspace = true
crabgresql-txn.workspace = true
crabgresql-types.workspace = true

[dev-dependencies]
anyhow.workspace = true
