//! `IMPLEMENTED_PRONAMES`: the function names this build actually resolves.
//!
//! A `pg_proc` row is a claim that the function exists. Most rows are justified
//! by an inbound reference from another catalog (`pg_type.typinput`,
//! `pg_operator.oprcode`, `pg_aggregate.aggfnoid`, …) — that census is what
//! [`crate::symbols::SymbolTable::references`] hands [`crate::pg_proc`]. The
//! rest of the SQL surface has no such reference: nothing in the vendored data
//! points at `upper`, `to_char` or `row_number`, yet a client that cannot find
//! them in `pg_proc` cannot introspect this server at all — `'upper'::regproc`
//! fails and `\df` comes back empty.
//!
//! So this list is the second justification: the names `crabgresql-binder`
//! resolves as a function of some kind. It is duplicated data, and the
//! duplication is checked rather than trusted —
//! `crabgresql-server`'s `pg_proc_surface` test walks every `proname` in
//! `pg_proc.dat` and compares this list against
//! `crabgresql_binder::implements_function` in both directions, so a function
//! added to the binder without a name here (or the reverse) fails the suite.
//!
//! Selection is by **name**, not by signature: a listed name publishes every
//! overload `pg_proc.dat` gives it, under upstream's OIDs. That is what makes
//! `\df upper` and `pg_proc` read as they do on PostgreSQL. The cost is a
//! documented over-claim in the other direction — upstream lists
//! `length(lseg)` alongside `length(text)`, and this build may implement only
//! some of a family — so a row means "this build implements this function",
//! not "this exact overload resolves".
//!
//! Three names the binder resolves are deliberately absent: `current_catalog`,
//! `current_role` and `user`. PostgreSQL's grammar spells those as keywords and
//! publishes no `pg_proc` row for either, so listing them would claim a
//! function upstream does not have — and `pg_proc.dat` defines no entry to
//! publish anyway.

/// The function names this build resolves, ascending. Sorted and duplicate-free
/// (see the test below), so [`crate::pg_proc`] can test membership by binary
/// search.
pub static IMPLEMENTED_PRONAMES: &[&str] = &[
    "abbrev",
    "abs",
    "acos",
    "acosd",
    "acosh",
    "age",
    "area",
    "array_agg",
    "array_append",
    "array_cat",
    "array_length",
    "array_prepend",
    "array_to_string",
    "array_to_tsvector",
    "array_upper",
    "ascii",
    "asin",
    "asind",
    "asinh",
    "atan",
    "atan2",
    "atan2d",
    "atand",
    "atanh",
    "avg",
    "bit_count",
    "bit_length",
    "booleq",
    "boolne",
    "bound_box",
    "box",
    "btrim",
    "cardinality",
    "cash_words",
    "cashlarger",
    "cashsmaller",
    "cbrt",
    "ceil",
    "ceiling",
    "center",
    "char_length",
    "character_length",
    "chr",
    "circle",
    "clock_timestamp",
    "col_description",
    "concat",
    "concat_ws",
    "cos",
    "cosd",
    "cosh",
    "cot",
    "cotd",
    "count",
    "crc32",
    "crc32c",
    "current_database",
    "current_schema",
    "current_schemas",
    "current_setting",
    "current_user",
    "currval",
    "date_bin",
    "date_part",
    "date_trunc",
    "decode",
    "degrees",
    "dense_rank",
    "diagonal",
    "diameter",
    "encode",
    "erf",
    "erfc",
    "exp",
    "family",
    "float4send",
    "float8send",
    "floor",
    "format",
    "format_type",
    "gamma",
    "gcd",
    "gen_random_uuid",
    "generate_series",
    "generate_subscripts",
    "get_bit",
    "height",
    "host",
    "initcap",
    "isclosed",
    "isfinite",
    "ishorizontal",
    "isopen",
    "isparallel",
    "isperp",
    "isvertical",
    "jsonb_path_exists",
    "jsonb_path_match",
    "jsonb_path_query",
    "jsonb_path_query_array",
    "jsonb_path_query_first",
    "justify_days",
    "justify_hours",
    "justify_interval",
    "lastval",
    "lcm",
    "left",
    "length",
    "lgamma",
    "line",
    "ln",
    "log",
    "log10",
    "lower",
    "lpad",
    "lseg",
    "ltrim",
    "macaddr8_set7bit",
    "make_date",
    "make_interval",
    "make_time",
    "make_timestamp",
    "make_timestamptz",
    "masklen",
    "max",
    "md5",
    "min",
    "mod",
    "network",
    "nextval",
    "now",
    "npoints",
    "numnode",
    "obj_description",
    "octet_length",
    "overlay",
    "path",
    "pclose",
    "pg_available_extension_versions",
    "pg_available_extensions",
    "pg_backend_pid",
    "pg_char_to_encoding",
    "pg_current_xact_id",
    "pg_current_xact_id_if_assigned",
    "pg_encoding_to_char",
    "pg_get_constraintdef",
    "pg_get_expr",
    "pg_get_indexdef",
    "pg_get_userbyid",
    "pg_get_viewdef",
    "pg_indexam_has_property",
    "pg_input_error_info",
    "pg_input_is_valid",
    "pg_is_in_recovery",
    "pg_is_other_temp_schema",
    "pg_lsn",
    "pg_my_temp_schema",
    "pg_partition_ancestors",
    "pg_postmaster_start_time",
    "pg_table_is_visible",
    "pg_tablespace_location",
    "pg_typeof",
    "pg_xact_status",
    "pi",
    "point",
    "polygon",
    "popen",
    "pow",
    "power",
    "pt_contained_circle",
    "pt_contained_poly",
    "querytree",
    "quote_ident",
    "quote_literal",
    "quote_nullable",
    "radians",
    "radius",
    "rank",
    "regexp_count",
    "regexp_like",
    "regexp_replace",
    "regexp_substr",
    "repeat",
    "replace",
    "reverse",
    "right",
    "round",
    "row_number",
    "rpad",
    "rtrim",
    "session_user",
    "set_bit",
    "setval",
    "setweight",
    "sha224",
    "sha256",
    "sha384",
    "sha512",
    "sign",
    "sin",
    "sind",
    "sinh",
    "slope",
    "split_part",
    "sqrt",
    "starts_with",
    "statement_timestamp",
    "string_agg",
    "strip",
    "strpos",
    "substr",
    "substring",
    "sum",
    "tan",
    "tand",
    "tanh",
    "tid_block",
    "tid_offset",
    "timezone",
    "to_char",
    "to_date",
    "to_hex",
    "to_number",
    "to_timestamp",
    "transaction_timestamp",
    "translate",
    "trunc",
    "ts_delete",
    "ts_filter",
    "tsquery_phrase",
    "tsvector_to_array",
    "txid_current",
    "txid_current_if_assigned",
    "unnest",
    "upper",
    "uuid_extract_timestamp",
    "uuid_extract_version",
    "uuidv4",
    "uuidv7",
    "version",
    "width",
    "xid8cmp",
];

#[cfg(test)]
mod tests {
    use super::IMPLEMENTED_PRONAMES;

    /// Sorted and duplicate-free: the membership test is a binary search, and a
    /// name listed twice would read as two claims about one function.
    #[test]
    fn the_manifest_is_sorted_and_unique() {
        for pair in IMPLEMENTED_PRONAMES.windows(2) {
            assert!(
                pair[0] < pair[1],
                "IMPLEMENTED_PRONAMES is out of order at {:?}",
                pair
            );
        }
    }
}
