//! `PG_AGGREGATE_ROWS` codegen: what makes an aggregate function an aggregate.
//!
//! A `pg_proc` row with `prokind = 'a'` says *that* a function aggregates; this
//! says *how* — the transition function that folds each row into the state, the
//! final function that turns the state into the answer, and the moving-window
//! variants a `WINDOW` frame needs to remove rows again.
//!
//! The relation has no `oid` column of its own: an aggregate is identified by
//! the `pg_proc` row it extends, so `aggfnoid` is both the primary key and the
//! reference. That is also why the key is written as a *signature* —
//! `avg(int8)` and `avg(int4)` are two different aggregates.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, get, str_field};
use crate::symbols::SymbolKind::{Operator, Type};
use crate::symbols::SymbolTable;

/// Emit `PG_AGGREGATE_ROWS` from `pg_aggregate.dat`, in file order for the
/// reason [`pg_amop::emit`](crate::pg_amop::emit) is.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_aggregate.dat\n");
    out.push_str("pub static PG_AGGREGATE_ROWS: &[PgAggregateRow] = &[\n");
    for e in entries {
        let key = str_field(e, "aggfnoid", "");
        // The aggregate itself, by signature. A bare name would be ambiguous
        // for all but a handful of them.
        let aggfnoid = crate::proc_ref_resolved(symbols, key)
            .unwrap_or_else(|| panic!("pg_aggregate: aggfnoid {key:?} names no pg_proc entry"));
        // Every support function is optional except `aggtransfn`, and `-` is
        // how the catalog spells an absent one — which is the rule
        // [`crate::proc_ref`] already carries, panic on a real name included.
        let support = |column: &str| crate::proc_ref(symbols, str_field(e, column, "-"));
        let type_oid = |column: &str| match get(e, column) {
            Some(name) => symbols.resolve_name(Type, name).unwrap_or_else(|| {
                panic!("pg_aggregate {key}: {column} names type {name:?}, which pg_type.dat lacks")
            }),
            None => 0,
        };
        let int_field = |column: &str, default: i64| match get(e, column) {
            Some(value) => value
                .parse::<i64>()
                .unwrap_or_else(|_| panic!("pg_aggregate {key}: bad {column} {value:?}")),
            None => default,
        };
        let _ = writeln!(
            out,
            "    PgAggregateRow {{ aggfnoid: {aggfnoid}, aggkind: {aggkind:?}, \
aggnumdirectargs: {numdirect}, aggtransfn: {transfn}, aggfinalfn: {finalfn}, \
aggcombinefn: {combinefn}, aggserialfn: {serialfn}, aggdeserialfn: {deserialfn}, \
aggmtransfn: {mtransfn}, aggminvtransfn: {minvtransfn}, aggmfinalfn: {mfinalfn}, \
aggfinalextra: {finalextra}, aggmfinalextra: {mfinalextra}, \
aggfinalmodify: {finalmodify:?}, aggmfinalmodify: {mfinalmodify:?}, \
aggsortop: {sortop}, aggtranstype: {transtype}, aggtransspace: {transspace}, \
aggmtranstype: {mtranstype}, aggmtransspace: {mtransspace}, \
agginitval: {initval:?}, aggminitval: {minitval:?} }},",
            // `n` is a plain aggregate, the BKI default; `o` is an ordered-set
            // one and `h` a hypothetical-set one, and only those two take
            // direct arguments.
            aggkind = str_field(e, "aggkind", "n"),
            numdirect = int_field("aggnumdirectargs", 0) as i16,
            transfn = support("aggtransfn"),
            finalfn = support("aggfinalfn"),
            combinefn = support("aggcombinefn"),
            serialfn = support("aggserialfn"),
            deserialfn = support("aggdeserialfn"),
            mtransfn = support("aggmtransfn"),
            minvtransfn = support("aggminvtransfn"),
            mfinalfn = support("aggmfinalfn"),
            finalextra = bool_field(e, "aggfinalextra", false),
            mfinalextra = bool_field(e, "aggmfinalextra", false),
            // `r` — the final function may not modify the state — is the
            // default; `s` and `w` are the weaker promises an aggregate makes
            // when it can afford to.
            finalmodify = str_field(e, "aggfinalmodify", "r"),
            mfinalmodify = str_field(e, "aggmfinalmodify", "r"),
            // `MIN`/`MAX` name the ordering operator they are equivalent to,
            // which is what lets the planner answer one from an index.
            sortop = match get(e, "aggsortop") {
                Some(reference) => symbols
                    .resolve_signature(Operator, reference)
                    .unwrap_or_else(|| panic!(
                        "pg_aggregate {key}: aggsortop {reference:?} names no pg_operator entry"
                    )),
                None => 0,
            },
            transtype = type_oid("aggtranstype"),
            transspace = int_field("aggtransspace", 0) as i32,
            mtranstype = type_oid("aggmtranstype"),
            mtransspace = int_field("aggmtransspace", 0) as i32,
            // The initial state, as its own text. Empty here means the column
            // is NULL, which is not the same as the empty string — that would
            // be an initial state of `''`, and no entry has one.
            initval = str_field(e, "agginitval", ""),
            minitval = str_field(e, "aggminitval", ""),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::{pg_operator, pg_proc};

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int8", 20);
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Type, "internal", 2281);
        symbols.define_name(Type, "numeric", 1700);
        pg_proc::define_symbols(
            &parse_dat(
                "[{ oid => '2100', proname => 'avg', proargtypes => 'int8' },\n\
                  { oid => '2101', proname => 'avg', proargtypes => 'int4' },\n\
                  { oid => '2103', proname => 'max', proargtypes => 'int4' },\n\
                  { oid => '1832', proname => 'int8_avg_accum', proargtypes => 'internal int8' },\n\
                  { oid => '3546', proname => 'numeric_poly_avg', proargtypes => 'internal' },\n\
                  { oid => '768', proname => 'int4larger', proargtypes => 'int4 int4' }]",
            ),
            &mut symbols,
        );
        pg_operator::define_symbols(
            &parse_dat("[{ oid => '97', oprname => '<', oprleft => 'int4', oprright => 'int4' }]"),
            &mut symbols,
        );
        symbols
    }

    #[test]
    fn the_key_is_a_signature_and_the_defaults_fill_the_rest() {
        let aggs = parse_dat(
            "[{ aggfnoid => 'avg(int8)', aggtransfn => 'int8_avg_accum', \
             aggfinalfn => 'numeric_poly_avg', aggtranstype => 'internal', \
             aggtransspace => '48' }]",
        );
        let emitted = emit(&aggs, &symbols());
        // `avg` names two aggregates; only the signature tells them apart, and
        // the regproc column still renders the bare name.
        assert!(emitted.contains("aggfnoid: ProcRef { oid: 2100, name: \"avg\" }"));
        assert!(emitted.contains("aggtransfn: ProcRef { oid: 1832, name: \"int8_avg_accum\" }"));
        assert!(emitted.contains("aggkind: \"n\""));
        assert!(emitted.contains("aggnumdirectargs: 0"));
        assert!(emitted.contains("aggfinalmodify: \"r\", aggmfinalmodify: \"r\""));
        assert!(emitted.contains("aggtranstype: 2281, aggtransspace: 48"));
        // No moving-window variant, and no initial state: both spelled as the
        // absence the catalog stores as NULL.
        assert!(emitted.contains("aggmtranstype: 0, aggmtransspace: 0"));
        assert!(emitted.contains("agginitval: \"\", aggminitval: \"\""));
    }

    #[test]
    fn a_sort_operator_resolves_to_the_operator_it_names() {
        // MAX is equivalent to ordering by `<` and taking the last row, which
        // is the fact that lets a planner answer it from an index.
        let aggs = parse_dat(
            "[{ aggfnoid => 'max(int4)', aggtransfn => 'int4larger', \
             aggcombinefn => 'int4larger', aggsortop => '<(int4,int4)', \
             aggtranstype => 'int4' }]",
        );
        let emitted = emit(&aggs, &symbols());
        assert!(emitted.contains("aggsortop: 97"));
        assert!(emitted.contains("aggcombinefn: ProcRef { oid: 768, name: \"int4larger\" }"));
        assert!(emitted.contains("aggfinalfn: ProcRef { oid: 0, name: \"-\" }"));
    }

    #[test]
    #[should_panic(expected = "names no pg_proc entry")]
    fn an_unresolvable_aggregate_fails_the_build() {
        let aggs = parse_dat("[{ aggfnoid => 'avg(float8)', aggtransfn => 'int4larger' }]");
        emit(&aggs, &symbols());
    }
}
