//! `PG_AMPROC_ROWS` codegen: the support functions an operator family needs
//! beyond its operators.
//!
//! Where `pg_amop` says which operator answers a strategy, this says which
//! *function* the access method calls to do its own work — btree's support
//! function 1 is the three-way comparison, hash's is the hash. It is the table
//! `\dAp` reads.
//!
//! No entry carries an `oid`, so every row is numbered by [`OidCounter`].

use std::fmt::Write as _;

use crate::OidCounter;
use crate::dat::{Entry, str_field};
use crate::symbols::SymbolKind::{Opfamily, Proc, Type};
use crate::symbols::SymbolTable;

/// Emit `PG_AMPROC_ROWS: &[PgAmprocRow]` from `pg_amproc.dat`, in file order
/// for the reason [`pg_amop::emit`](crate::pg_amop::emit) is.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_amproc.dat\n");
    out.push_str("pub static PG_AMPROC_ROWS: &[PgAmprocRow] = &[\n");
    let mut oids = OidCounter::default();
    for e in entries {
        let oid = oids.of(e);
        let family = str_field(e, "amprocfamily", "");
        let proc = str_field(e, "amproc", "");
        let _ = writeln!(
            out,
            "    PgAmprocRow {{ oid: {oid}, amprocfamily: {amprocfamily}, \
amproclefttype: {lefttype}, amprocrighttype: {righttype}, amprocnum: {num}, \
amproc: {amproc} }},",
            amprocfamily = symbols.resolve_name(Opfamily, family).unwrap_or_else(|| {
                panic!(
                    "pg_amproc references operator family {family:?}, which pg_opfamily.dat lacks"
                )
            }),
            lefttype = type_oid(symbols, str_field(e, "amproclefttype", "")),
            righttype = type_oid(symbols, str_field(e, "amprocrighttype", "")),
            num = str_field(e, "amprocnum", "")
                .parse::<i16>()
                .unwrap_or_else(|_| panic!("pg_amproc {proc}: bad amprocnum")),
            amproc = amproc_ref(symbols, proc),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

/// The `ProcRef` an entry's `amproc` names.
///
/// The column is declared `regproc`, and the data writes it the two ways a
/// `regproc`-ish reference is written anywhere in these files: as a bare name
/// where that is unambiguous, and as a full signature (`btint84cmp(int8,int4)`)
/// where the name alone names more than one function. `pg_cast.castfunc` takes
/// the same two spellings.
///
/// The printed name drops the argument list, because that is what `regproc`
/// output renders — the signature is how the reference is *written*, not what
/// the column shows.
fn amproc_ref(symbols: &SymbolTable, reference: &str) -> String {
    let oid = if reference.contains('(') {
        symbols.resolve_signature(Proc, reference)
    } else {
        symbols.resolve_name(Proc, reference)
    }
    .unwrap_or_else(|| panic!("pg_amproc: amproc {reference:?} names no pg_proc entry"));
    let name = reference.split('(').next().unwrap_or(reference);
    format!("ProcRef {{ oid: {oid}, name: {name:?} }}")
}

fn type_oid(symbols: &SymbolTable, name: &str) -> u32 {
    symbols
        .resolve_name(Type, name)
        .unwrap_or_else(|| panic!("pg_amproc references type {name:?}, which pg_type.dat lacks"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::pg_proc;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int2", 21);
        symbols.define_name(Type, "int8", 20);
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Opfamily, "btree/integer_ops", 1976);
        pg_proc::define_symbols(
            &parse_dat(
                "[{ oid => '350', proname => 'btint2cmp', proargtypes => 'int2 int2' },\n\
                  { oid => '3129', proname => 'btint84cmp', proargtypes => 'int8 int4' },\n\
                  { oid => '3130', proname => 'btint84cmp', proargtypes => 'int4 int8' }]",
            ),
            &mut symbols,
        );
        symbols
    }

    #[test]
    fn a_bare_name_and_a_signature_both_resolve() {
        let amprocs = parse_dat(
            "[{ amprocfamily => 'btree/integer_ops', amproclefttype => 'int2', \
             amprocrighttype => 'int2', amprocnum => '1', amproc => 'btint2cmp' },\n\
              { amprocfamily => 'btree/integer_ops', amproclefttype => 'int8', \
             amprocrighttype => 'int4', amprocnum => '1', \
             amproc => 'btint84cmp(int8,int4)' }]",
        );
        let emitted = emit(&amprocs, &symbols());
        assert!(emitted.contains(
            "oid: 10000, amprocfamily: 1976, amproclefttype: 21, amprocrighttype: 21, \
             amprocnum: 1, amproc: ProcRef { oid: 350, name: \"btint2cmp\" }"
        ));
        // The name a signature reference prints as is the bare one: a `regproc`
        // column renders the function's name, not the reference's spelling.
        assert!(emitted.contains("oid: 10001,"));
        assert!(emitted.contains("amproc: ProcRef { oid: 3129, name: \"btint84cmp\" }"));
    }

    #[test]
    #[should_panic(expected = "names no pg_proc entry")]
    fn an_ambiguous_bare_name_fails_the_build() {
        // `btint84cmp` is defined twice, so the bare name resolves to nothing —
        // which is exactly why the real file writes that one as a signature.
        let amprocs = parse_dat(
            "[{ amprocfamily => 'btree/integer_ops', amproclefttype => 'int8', \
             amprocrighttype => 'int4', amprocnum => '1', amproc => 'btint84cmp' }]",
        );
        emit(&amprocs, &symbols());
    }
}
