//! `PG_AMOP_ROWS` codegen: which operator implements which strategy of an
//! operator family.
//!
//! `pg_opclass`/`pg_opfamily` say a type can be indexed; this says *how* —
//! that btree strategy 1 for `integer_ops` is `<(int4,int4)`. It is the table
//! `\dAo` reads, and the one an index method consults to turn a `WHERE` clause
//! into a scan key.
//!
//! No entry carries an `oid`, so every row is numbered by [`OidCounter`].

use std::fmt::Write as _;

use crate::dat::{Entry, get, str_field};
use crate::symbols::SymbolKind::{Operator, Opfamily, Type};
use crate::symbols::SymbolTable;
use crate::{OidCounter, am_oid};

/// Emit `PG_AMOP_ROWS: &[PgAmopRow]` from `pg_amop.dat`, in file order — the
/// order upstream inserts the rows in, and so the order a client reading the
/// relation without `ORDER BY` sees them.
///
/// Every entry is emitted, including those of access methods this build has no
/// index for. The row is a statement about what upstream's `gist` can do with
/// the type, which is true whether or not this server can build the index —
/// the same reading `pg_opclass` already takes.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_amop.dat\n");
    out.push_str("pub static PG_AMOP_ROWS: &[PgAmopRow] = &[\n");
    let mut oids = OidCounter::default();
    for e in entries {
        let oid = oids.of(e);
        let family = str_field(e, "amopfamily", "");
        let opr = str_field(e, "amopopr", "");
        let _ = writeln!(
            out,
            "    PgAmopRow {{ oid: {oid}, amopfamily: {amopfamily}, \
amoplefttype: {lefttype}, amoprighttype: {righttype}, amopstrategy: {strategy}, \
amoppurpose: {purpose:?}, amopopr: {amopopr}, amopmethod: {method}, \
amopsortfamily: {sortfamily} }},",
            amopfamily = opfamily_oid(symbols, family),
            lefttype = type_oid(symbols, str_field(e, "amoplefttype", "")),
            righttype = type_oid(symbols, str_field(e, "amoprighttype", "")),
            strategy = str_field(e, "amopstrategy", "")
                .parse::<i16>()
                .unwrap_or_else(|_| panic!("pg_amop {opr}: bad amopstrategy")),
            // `s` is a search operator, the BKI default; `o` is an ordering
            // one, which is the only case that also names a sort family.
            purpose = str_field(e, "amoppurpose", "s"),
            amopopr = symbols
                .resolve_signature(Operator, opr)
                .unwrap_or_else(|| panic!("pg_amop: amopopr {opr:?} names no pg_operator entry")),
            method = am_oid(str_field(e, "amopmethod", "")),
            sortfamily = get(e, "amopsortfamily").map_or(0, |f| opfamily_oid(symbols, f)),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

fn opfamily_oid(symbols: &SymbolTable, name: &str) -> u32 {
    symbols.resolve_name(Opfamily, name).unwrap_or_else(|| {
        panic!("pg_amop references operator family {name:?}, which pg_opfamily.dat lacks")
    })
}

fn type_oid(symbols: &SymbolTable, name: &str) -> u32 {
    symbols
        .resolve_name(Type, name)
        .unwrap_or_else(|| panic!("pg_amop references type {name:?}, which pg_type.dat lacks"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::pg_operator;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int2", 21);
        symbols.define_name(Type, "float8", 701);
        symbols.define_name(Type, "point", 600);
        symbols.define_name(Opfamily, "btree/integer_ops", 1976);
        symbols.define_name(Opfamily, "btree/float_ops", 1970);
        symbols.define_name(Opfamily, "gist/point_ops", 1029);
        pg_operator::define_symbols(
            &parse_dat(
                "[{ oid => '95', oprname => '<', oprleft => 'int2', oprright => 'int2' },\n\
                  { oid => '517', oprname => '<->', oprleft => 'point', oprright => 'point' }]",
            ),
            &mut symbols,
        );
        symbols
    }

    #[test]
    fn a_search_operator_takes_the_bki_defaults() {
        let amops = parse_dat(
            "[{ amopfamily => 'btree/integer_ops', amoplefttype => 'int2', \
             amoprighttype => 'int2', amopstrategy => '1', amopopr => '<(int2,int2)', \
             amopmethod => 'btree' }]",
        );
        let emitted = emit(&amops, &symbols());
        assert!(emitted.contains(
            "oid: 10000, amopfamily: 1976, amoplefttype: 21, amoprighttype: 21, \
             amopstrategy: 1, amoppurpose: \"s\", amopopr: 95, amopmethod: 403, \
             amopsortfamily: 0"
        ));
    }

    #[test]
    fn an_ordering_operator_names_the_family_it_sorts_by() {
        // The eight `o` entries in the real file are gist distance operators,
        // and the sort family is a reference like any other — resolving it is
        // what keeps `\dAo` from printing a dangling OID.
        let amops = parse_dat(
            "[{ amopfamily => 'gist/point_ops', amoplefttype => 'point', \
             amoprighttype => 'point', amopstrategy => '15', amopopr => '<->(point,point)', \
             amopmethod => 'gist', amoppurpose => 'o', amopsortfamily => 'btree/float_ops' }]",
        );
        let emitted = emit(&amops, &symbols());
        assert!(emitted.contains("amoppurpose: \"o\""));
        assert!(emitted.contains("amopsortfamily: 1970"));
    }

    #[test]
    #[should_panic(expected = "names no pg_operator entry")]
    fn an_unresolvable_operator_fails_the_build() {
        let amops = parse_dat(
            "[{ amopfamily => 'btree/integer_ops', amoplefttype => 'int2', \
             amoprighttype => 'int2', amopstrategy => '1', amopopr => '<(int8,int8)', \
             amopmethod => 'btree' }]",
        );
        emit(&amops, &symbols());
    }
}
