//! `PG_CONVERSION_ROWS` codegen: the built-in encoding conversions.
//!
//! A row names the function that recodes a string from one server encoding to
//! another. Every entry carries an explicit `oid`, so nothing here is numbered.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, str_field};
use crate::symbols::SymbolTable;

/// The encoding an entry names as `PG_<name>`, with the prefix — the `.dat`'s
/// own spelling — stripped off.
///
/// The *number* is deliberately not resolved here. PostgreSQL's numbering is a
/// run-time fact `crabgresql-types` already owns (`encoding::char_to_encoding`,
/// transcribed from `pg_encoding_to_char` on a stock 18.4), and a second copy
/// of that 42-entry table in this crate is a copy nothing keeps in step. So the
/// generated row carries the name and `crabgresql-catalog`'s
/// `catalogs::conversion` turns it into a number through the one table.
///
/// The prefix itself is codegen's business, and an entry without it is a `.dat`
/// this scanner does not understand — so that fails the build.
fn encoding_name(symbol: &str) -> &str {
    symbol
        .strip_prefix("PG_")
        .unwrap_or_else(|| panic!("pg_conversion: {symbol:?} is not a PG_<encoding> symbol"))
}

/// Emit `PG_CONVERSION_ROWS: &[PgConversionRow]` from `pg_conversion.dat`, in
/// file order.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by crabgresql-bki from vendor/postgres/catalog/pg_conversion.dat\n",
    );
    out.push_str("pub static PG_CONVERSION_ROWS: &[PgConversionRow] = &[\n");
    for e in entries {
        let conname = str_field(e, "conname", "");
        let proc = str_field(e, "conproc", "");
        let _ = writeln!(
            out,
            "    PgConversionRow {{ oid: {oid}, conname: {conname:?}, \
conforencoding: {from:?}, contoencoding: {to:?}, conproc: {conproc}, \
condefault: {condefault} }},",
            oid = crate::dat::oid_field(e, "oid"),
            from = encoding_name(str_field(e, "conforencoding", "")),
            to = encoding_name(str_field(e, "contoencoding", "")),
            conproc = crate::proc_ref_resolved(symbols, proc).unwrap_or_else(|| panic!(
                "pg_conversion {conname}: conproc {proc:?} names no pg_proc entry"
            )),
            // Every built-in conversion is the default for its pair; no entry
            // says otherwise, and the BKI default agrees.
            condefault = bool_field(e, "condefault", true),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::pg_proc;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        pg_proc::define_symbols(
            &parse_dat("[{ oid => '4410', proname => 'koi8r_to_win1251' }]"),
            &mut symbols,
        );
        symbols
    }

    #[test]
    fn the_row_carries_the_encoding_name_without_its_prefix() {
        let conversions = parse_dat(
            "[{ oid => '4410', conname => 'koi8_r_to_windows_1251', \
             conforencoding => 'PG_KOI8R', contoencoding => 'PG_WIN1251', \
             conproc => 'koi8r_to_win1251' }]",
        );
        let emitted = emit(&conversions, &symbols());
        // The numbers are `crabgresql-catalog`'s to resolve, through the one
        // table `crabgresql-types` owns; see
        // `pg_conversion_numbers_the_encodings_it_converts_between` there.
        assert!(emitted.contains(
            "oid: 4410, conname: \"koi8_r_to_windows_1251\", conforencoding: \"KOI8R\", \
             contoencoding: \"WIN1251\", conproc: ProcRef { oid: 4410, name: \"koi8r_to_win1251\" }, \
             condefault: true"
        ));
    }

    #[test]
    #[should_panic(expected = "is not a PG_<encoding> symbol")]
    fn an_unprefixed_encoding_fails_the_build() {
        // A name that resolves to no encoding is caught in the catalog crate,
        // which owns the numbering; what codegen can judge is the spelling.
        let conversions = parse_dat(
            "[{ oid => '1', conname => 'c', conforencoding => 'KOI8R', \
             contoencoding => 'PG_UTF8', conproc => 'koi8r_to_win1251' }]",
        );
        emit(&conversions, &symbols());
    }
}
