//! `PG_CAST_ROWS` codegen. `pg_cast` defines no symbols of its own — upstream
//! assigns its rows no OIDs — so it takes part in phase two only.

use std::fmt::Write as _;

use crate::dat::{Entry, get, str_field};
use crate::symbols::SymbolKind::{Proc, Type};
use crate::symbols::SymbolTable;

/// Emit `PG_CAST_ROWS: &[PgCastRow]` from `pg_cast.dat`. `castsource`/
/// `casttarget` are written as type names (resolved here against `pg_type`);
/// a cast whose source or target is a type crabgresql does not expose is
/// skipped, so the emitted `pg_cast` stays consistent with the exposed
/// `pg_type`. `castfunc` is a resolved `pg_proc` OID, as PostgreSQL declares
/// the column — see [`resolve_castfunc`].
///
/// No entry carries an `oid`: upstream's codegen numbers the whole catalog,
/// and these are those numbers rather than invented ones — see
/// [`pg_opclass`](crate::pg_opclass) for the rule and how it was checked. The
/// counter therefore advances on **every** entry, including the ones skipped
/// above: a skipped cast still spends its number upstream, and not spending it
/// here would shift every OID after it off PostgreSQL's.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    /// Where upstream's generated OIDs begin, per catalog.
    const FIRST_CAST_OID: u32 = 10000;
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_cast.dat\n");
    out.push_str("pub static PG_CAST_ROWS: &[PgCastRow] = &[\n");
    for (position, e) in entries.iter().enumerate() {
        // No entry is numbered upstream, so an entry's OID is its position —
        // counted over the whole file, not over the rows that survive the skip
        // below.
        let oid = FIRST_CAST_OID + position as u32;
        let (Some(source), Some(target)) = (
            get(e, "castsource").and_then(|n| symbols.resolve_name(Type, n)),
            get(e, "casttarget").and_then(|n| symbols.resolve_name(Type, n)),
        ) else {
            continue; // references a type we do not expose
        };
        let row = format!(
            "    PgCastRow {{ oid: {oid}, castsource: {source}, casttarget: {target}, \
castfunc: {castfunc}, castcontext: {castcontext:?}, castmethod: {castmethod:?} }},\n",
            castfunc = resolve_castfunc(symbols, e),
            castcontext = str_field(e, "castcontext", "e"),
            castmethod = str_field(e, "castmethod", "f"),
        );
        out.push_str(&row);
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

/// The `pg_proc` OID an entry's `castfunc` names. The column is a
/// `regprocedure`, and `pg_cast.dat` writes it two ways: as a full signature
/// (`int4(int2)`) where the name alone would be ambiguous, and as a bare name
/// (`oid`, `xml`, `path`) where it is not — the same rule the catalog applies
/// to a `regproc` column, which [`SymbolTable::resolve_name`] already carries,
/// since a name defined twice resolves to nothing.
///
/// `0` is upstream's spelling of a binary-coercible cast, which needs no
/// function. Anything else that fails to resolve is a reference into a catalog
/// this build claims to have generated, so it fails the build rather than
/// emitting a function cast whose function is `-`.
fn resolve_castfunc(symbols: &SymbolTable, e: &Entry) -> u32 {
    let reference = str_field(e, "castfunc", "0");
    if reference == "0" {
        return 0;
    }
    let oid = if reference.contains('(') {
        symbols.resolve_signature(Proc, reference)
    } else {
        symbols.resolve_name(Proc, reference)
    };
    oid.unwrap_or_else(|| {
        panic!(
            "pg_cast {} -> {}: castfunc {reference:?} names no pg_proc entry",
            str_field(e, "castsource", "?"),
            str_field(e, "casttarget", "?"),
        )
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int2", 21);
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Type, "int8", 20);
        symbols.define_name(Type, "oid", 26);
        symbols.define_signature(Proc, "int4", "int2", 313);
        // `oid(int8)`, which pg_cast.dat references by its bare name.
        symbols.define_name(Proc, "oid", 1287);
        symbols.define_signature(Proc, "oid", "int8", 1287);
        symbols
    }

    #[test]
    fn resolves_names_and_numbers_the_rows() {
        let casts = parse_dat(
            "[{ castsource => 'int2', casttarget => 'int4', castfunc => 'int4(int2)', \
             castcontext => 'i', castmethod => 'f' },\n\
              { castsource => 'int4', casttarget => 'oid', castfunc => '0', \
             castcontext => 'i', castmethod => 'b' }]",
        );
        let emitted = emit(&casts, &symbols());
        assert!(emitted.contains(
            "PgCastRow { oid: 10000, castsource: 21, casttarget: 23, castfunc: 313, \
             castcontext: \"i\", castmethod: \"f\" }"
        ));
        // A binary-coercible cast keeps `castfunc: 0`, and OIDs run on.
        assert!(emitted.contains(
            "PgCastRow { oid: 10001, castsource: 23, casttarget: 26, castfunc: 0, \
             castcontext: \"i\", castmethod: \"b\" }"
        ));
    }

    #[test]
    fn a_castfunc_written_as_a_bare_name_resolves() {
        // `{ castsource => 'int8', casttarget => 'oid', castfunc => 'oid' }` —
        // the spelling pg_cast.dat uses where the name is unambiguous.
        let casts = parse_dat(
            "[{ castsource => 'int8', casttarget => 'oid', castfunc => 'oid', \
             castcontext => 'i', castmethod => 'f' }]",
        );
        let emitted = emit(&casts, &symbols());
        assert!(emitted.contains("castfunc: 1287"));
    }

    #[test]
    #[should_panic(expected = "names no pg_proc entry")]
    fn an_unresolvable_castfunc_fails_the_build() {
        let casts =
            parse_dat("[{ castsource => 'int2', casttarget => 'int4', castfunc => 'nosuchfunc' }]");
        emit(&casts, &symbols());
    }

    #[test]
    fn a_cast_to_an_unexposed_type_is_skipped_but_spends_its_oid() {
        // Upstream numbers the entry whether or not this build has the type,
        // so the cast after a skipped one keeps PostgreSQL's OID rather than
        // sliding down into the skipped one's.
        let casts = parse_dat(
            "[{ castsource => 'int2', casttarget => 'money' },\n\
              { castsource => 'int2', casttarget => 'int4', castfunc => 'int4(int2)' }]",
        );
        let emitted = emit(&casts, &symbols());
        assert_eq!(emitted.matches("PgCastRow {").count(), 1);
        assert!(emitted.contains("PgCastRow { oid: 10001, castsource: 21, casttarget: 23,"));
    }
}
