//! `PG_CONVERSION_ROWS` codegen: the built-in encoding conversions.
//!
//! A row names the function that recodes a string from one server encoding to
//! another. Every entry carries an explicit `oid`, so nothing here is numbered.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, str_field};
use crate::symbols::SymbolTable;

/// PostgreSQL's encoding numbers, which `pg_conversion.conforencoding` and
/// `contoencoding` store. The `.dat` writes them symbolically — `PG_KOI8R` is
/// the `PG_` prefix plus the encoding's name — and the numbers themselves live
/// in a C header this crate does not read.
///
/// So they are recorded here, in the order that *is* the numbering: the list
/// below is what `pg_encoding_to_char(0..41)` reports on PostgreSQL 18.4, which
/// is the same fact the header states and the one a client can observe. An
/// encoding a bumped `.dat` names and this list lacks fails the build rather
/// than emitting a conversion between something and nothing.
const ENCODINGS: [&str; 42] = [
    "SQL_ASCII",
    "EUC_JP",
    "EUC_CN",
    "EUC_KR",
    "EUC_TW",
    "EUC_JIS_2004",
    "UTF8",
    "MULE_INTERNAL",
    "LATIN1",
    "LATIN2",
    "LATIN3",
    "LATIN4",
    "LATIN5",
    "LATIN6",
    "LATIN7",
    "LATIN8",
    "LATIN9",
    "LATIN10",
    "WIN1256",
    "WIN1258",
    "WIN866",
    "WIN874",
    "KOI8R",
    "WIN1251",
    "WIN1252",
    "ISO_8859_5",
    "ISO_8859_6",
    "ISO_8859_7",
    "ISO_8859_8",
    "WIN1250",
    "WIN1253",
    "WIN1254",
    "WIN1255",
    "WIN1257",
    "KOI8U",
    "SJIS",
    "BIG5",
    "GBK",
    "UHC",
    "GB18030",
    "JOHAB",
    "SHIFT_JIS_2004",
];

/// The number of the encoding an entry names as `PG_<name>`.
fn encoding_number(symbol: &str) -> i32 {
    let name = symbol
        .strip_prefix("PG_")
        .unwrap_or_else(|| panic!("pg_conversion: {symbol:?} is not a PG_<encoding> symbol"));
    ENCODINGS
        .iter()
        .position(|e| *e == name)
        .unwrap_or_else(|| panic!("pg_conversion: no encoding number known for {name:?}"))
        as i32
}

/// Emit `PG_CONVERSION_ROWS: &[PgConversionRow]` from `pg_conversion.dat`, in
/// file order.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated by crabgresql-bki from vendor/postgres/catalog/pg_conversion.dat\n",
    );
    out.push_str("pub static PG_CONVERSION_ROWS: &[PgConversionRow] = &[\n");
    for e in entries {
        let conname = str_field(e, "conname", "");
        let proc = str_field(e, "conproc", "");
        let _ = writeln!(
            out,
            "    PgConversionRow {{ oid: {oid}, conname: {conname:?}, \
conforencoding: {from}, contoencoding: {to}, conproc: {conproc}, \
condefault: {condefault} }},",
            oid = crate::dat::oid_field(e, "oid"),
            from = encoding_number(str_field(e, "conforencoding", "")),
            to = encoding_number(str_field(e, "contoencoding", "")),
            conproc = crate::proc_ref_resolved(symbols, proc).unwrap_or_else(|| panic!(
                "pg_conversion {conname}: conproc {proc:?} names no pg_proc entry"
            )),
            // Every built-in conversion is the default for its pair; no entry
            // says otherwise, and the BKI default agrees.
            condefault = bool_field(e, "condefault", true),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::pg_proc;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        pg_proc::define_symbols(
            &parse_dat("[{ oid => '4410', proname => 'koi8r_to_win1251' }]"),
            &mut symbols,
        );
        symbols
    }

    #[test]
    fn encodings_resolve_to_their_numbers() {
        let conversions = parse_dat(
            "[{ oid => '4410', conname => 'koi8_r_to_windows_1251', \
             conforencoding => 'PG_KOI8R', contoencoding => 'PG_WIN1251', \
             conproc => 'koi8r_to_win1251' }]",
        );
        let emitted = emit(&conversions, &symbols());
        assert!(emitted.contains(
            "oid: 4410, conname: \"koi8_r_to_windows_1251\", conforencoding: 22, \
             contoencoding: 23, conproc: ProcRef { oid: 4410, name: \"koi8r_to_win1251\" }, \
             condefault: true"
        ));
    }

    #[test]
    #[should_panic(expected = "no encoding number known")]
    fn an_unknown_encoding_fails_the_build() {
        let conversions = parse_dat(
            "[{ oid => '1', conname => 'c', conforencoding => 'PG_NOSUCH', \
             contoencoding => 'PG_UTF8', conproc => 'koi8r_to_win1251' }]",
        );
        emit(&conversions, &symbols());
    }
}
