//! `PG_CAST_ROWS` codegen. `pg_cast` defines no symbols of its own — upstream
//! assigns its rows no OIDs — so it takes part in phase two only.

use std::fmt::Write as _;

use crate::dat::{Entry, get, str_field};
use crate::symbols::SymbolKind::{Proc, Type};
use crate::symbols::SymbolTable;

/// Emit `PG_CAST_ROWS: &[PgCastRow]` from `pg_cast.dat`. `castsource`/
/// `casttarget` are written as type names (resolved here against `pg_type`);
/// a cast whose source or target is a type crabgresql does not expose is
/// skipped, so the emitted `pg_cast` stays consistent with the exposed
/// `pg_type`. OIDs are synthetic (upstream assigns none). `castfunc` is a
/// resolved `pg_proc` OID, as PostgreSQL declares the column — `0` for a
/// binary-coercible cast, which needs no function.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    // Casts have no manual OIDs upstream; assign stable synthetic ones above the
    // built-in floor so they never collide with a real object OID.
    const FIRST_CAST_OID: u32 = 10000;
    let mut out = String::new();
    out.push_str("// @generated by build.rs from vendor/postgres/catalog/pg_cast.dat\n");
    out.push_str("pub static PG_CAST_ROWS: &[PgCastRow] = &[\n");
    let mut next_oid = FIRST_CAST_OID;
    for e in entries {
        let (Some(source), Some(target)) = (
            get(e, "castsource").and_then(|n| symbols.resolve_name(Type, n)),
            get(e, "casttarget").and_then(|n| symbols.resolve_name(Type, n)),
        ) else {
            continue; // references a type we do not expose
        };
        let row = format!(
            "    PgCastRow {{ oid: {oid}, castsource: {source}, casttarget: {target}, \
castfunc: {castfunc}, castcontext: {castcontext:?}, castmethod: {castmethod:?} }},\n",
            oid = next_oid,
            castfunc = symbols
                .resolve_signature(Proc, str_field(e, "castfunc", "0"))
                .unwrap_or(0),
            castcontext = str_field(e, "castcontext", "e"),
            castmethod = str_field(e, "castmethod", "f"),
        );
        next_oid += 1;
        out.push_str(&row);
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int2", 21);
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Type, "oid", 26);
        symbols.define_signature(Proc, "int4", "int2", 313);
        symbols
    }

    #[test]
    fn resolves_names_and_numbers_the_rows() {
        let casts = parse_dat(
            "[{ castsource => 'int2', casttarget => 'int4', castfunc => 'int4(int2)', \
             castcontext => 'i', castmethod => 'f' },\n\
              { castsource => 'int4', casttarget => 'oid', castfunc => '0', \
             castcontext => 'i', castmethod => 'b' }]",
        );
        let emitted = emit(&casts, &symbols());
        assert!(emitted.contains(
            "PgCastRow { oid: 10000, castsource: 21, casttarget: 23, castfunc: 313, \
             castcontext: \"i\", castmethod: \"f\" }"
        ));
        // A binary-coercible cast keeps `castfunc: 0`, and OIDs run on.
        assert!(emitted.contains(
            "PgCastRow { oid: 10001, castsource: 23, casttarget: 26, castfunc: 0, \
             castcontext: \"i\", castmethod: \"b\" }"
        ));
    }

    #[test]
    fn a_cast_to_an_unexposed_type_is_skipped() {
        let casts = parse_dat("[{ castsource => 'int2', casttarget => 'money' }]");
        let emitted = emit(&casts, &symbols());
        assert!(!emitted.contains("PgCastRow {"));
    }
}
