//! `PG_DESCRIPTION_ROWS` codegen: the comments PostgreSQL ships on its own
//! built-in objects.
//!
//! Every `.dat` entry may carry a `descr` field, and PostgreSQL's `initdb`
//! turns each one into a `pg_description` row describing the object the entry
//! defines. This is the only reader of that field.
//!
//! A description is a claim that the object exists, so every source names how
//! to filter itself down to the rows this build publishes. What no `.dat` can
//! answer for — the catalogs whose rows are hand-written — is filtered in
//! `crabgresql-catalog`'s `catalogs::description`.

use std::fmt::Write as _;

use crate::dat::{Entry, get, oid_field};

/// One `.dat` file's worth of descriptions.
pub struct Source<'a> {
    /// The `pg_catalog` relation the described objects live in, by name: the
    /// fixed relation OIDs are `crabgresql-catalog`'s registry to own, not
    /// codegen's to duplicate.
    pub catalog: &'a str,
    pub entries: &'a [Entry],
    /// The OIDs worth describing, ascending, or `None` for "every entry in the
    /// file". This is the census for `pg_proc`, whose `.dat` describes some
    /// 2600 functions where this build publishes a few hundred.
    pub keep: Option<&'a [u32]>,
}

/// Emit `PG_DESCRIPTION_ROWS`, ordered so a `.dat` resync shows up as a
/// readable diff.
pub fn emit(sources: &[Source]) -> String {
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/*.dat\n");
    out.push_str("pub static PG_DESCRIPTION_ROWS: &[PgDescriptionRow] = &[\n");
    let mut sources: Vec<&Source> = sources.iter().collect();
    sources.sort_by_key(|s| s.catalog);
    for source in sources {
        let mut rows: Vec<(u32, String)> = Vec::new();
        for e in source.entries {
            let Some(descr) = get(e, "descr") else {
                continue;
            };
            let oid = oid_field(e, "oid");
            if source
                .keep
                .is_some_and(|keep| keep.binary_search(&oid).is_err())
            {
                continue;
            }
            rows.push((
                oid,
                format!(
                    "    PgDescriptionRow {{ catalog: {catalog:?}, objoid: {oid}, \
description: {descr:?} }},\n",
                    catalog = source.catalog,
                ),
            ));
        }
        rows.sort_by_key(|(oid, _)| *oid);
        for (_, row) in &rows {
            out.push_str(row);
        }
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    #[test]
    fn a_filtered_source_describes_only_the_rows_something_publishes() {
        let entries = parse_dat(
            "[{ oid => '1242', descr => 'I/O', proname => 'boolin' },\n\
              { oid => '1243', descr => 'I/O', proname => 'boolout' }]",
        );
        let emitted = emit(&[Source {
            catalog: "pg_proc",
            entries: &entries,
            keep: Some(&[1243]),
        }]);
        assert!(emitted.contains("objoid: 1243"));
        assert!(!emitted.contains("objoid: 1242"));
    }

    #[test]
    fn an_entry_without_a_descr_gets_no_row() {
        let entries = parse_dat("[{ oid => '16', typname => 'bool' }]");
        let emitted = emit(&[Source {
            catalog: "pg_type",
            entries: &entries,
            keep: None,
        }]);
        // Only the array's declaration, no rows inside it.
        assert!(!emitted.contains("objoid"));
    }

    #[test]
    fn an_escaped_quote_survives_into_the_literal() {
        // `bool`'s own description, as `pg_type.dat` writes it. The scanner
        // undoes the `.dat` escape and Rust's `{:?}` leaves a single quote
        // alone inside a string literal, so what lands in the generated file is
        // the text PostgreSQL prints.
        let entries = parse_dat(
            "[{ oid => '16', typname => 'bool', \
             descr => 'boolean, format \\'t\\'/\\'f\\'' }]",
        );
        let emitted = emit(&[Source {
            catalog: "pg_type",
            entries: &entries,
            keep: None,
        }]);
        assert!(emitted.contains(r#"description: "boolean, format 't'/'f'""#));
    }

    #[test]
    fn rows_are_grouped_by_catalog_and_sorted_by_oid() {
        let types = parse_dat("[{ oid => '25', descr => 'b' }, { oid => '16', descr => 'a' }]");
        let namespaces = parse_dat("[{ oid => '11', descr => 'ns' }]");
        let emitted = emit(&[
            Source {
                catalog: "pg_type",
                entries: &types,
                keep: None,
            },
            Source {
                catalog: "pg_namespace",
                entries: &namespaces,
                keep: None,
            },
        ]);
        let order: Vec<&str> = emitted.lines().filter(|l| l.contains("objoid")).collect();
        assert_eq!(order.len(), 3);
        assert!(order[0].contains("pg_namespace"));
        assert!(order[1].contains("objoid: 16"));
        assert!(order[2].contains("objoid: 25"));
    }
}
