//! `PG_OPFAMILY_ROWS` codegen.
//!
//! An operator family groups the operator classes that can be mixed in one
//! index expression. It carries no data beyond its name and access method —
//! what makes it worth generating is that `pg_opclass.opcfamily` points at one,
//! and a dangling reference there is what a client joining the two would find.

use std::fmt::Write as _;

use crate::am_oid;
use crate::dat::{Entry, get, oid_field, str_field};
use crate::symbols::SymbolKind::Opfamily;
use crate::symbols::SymbolTable;

/// Phase one: every family, under the `<method>/<name>` spelling
/// `pg_opclass.opcfamily` references it by — see [`SymbolKind::Opfamily`].
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        symbols.define_name(Opfamily, &family_key(e), oid_field(e, "oid"));
    }
}

/// Emit `PG_OPFAMILY_ROWS: &[PgOpfamilyRow]` from `pg_opfamily.dat`, in file
/// order for the reason [`pg_opclass::emit`](crate::pg_opclass::emit) is.
///
/// Every entry carries an explicit `oid`, so unlike `pg_opclass` there is
/// nothing to assign here.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_opfamily.dat\n");
    out.push_str("pub static PG_OPFAMILY_ROWS: &[PgOpfamilyRow] = &[\n");
    for e in entries {
        let key = family_key(e);
        let oid = symbols
            .resolve_name(Opfamily, &key)
            .unwrap_or_else(|| panic!("pg_opfamily entry {key:?} defines no unique oid"));
        let _ = writeln!(
            out,
            "    PgOpfamilyRow {{ oid: {oid}, opfmethod: {method}, opfname: {name:?} }},",
            method = am_oid(str_field(e, "opfmethod", "")),
            name = str_field(e, "opfname", ""),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

fn family_key(e: &Entry) -> String {
    let method = get(e, "opfmethod").expect("pg_opfamily entry without opfmethod");
    let name = get(e, "opfname").expect("pg_opfamily entry without opfname");
    format!("{method}/{name}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    #[test]
    fn a_family_is_keyed_by_method_and_name() {
        // `array_ops` exists under three methods; only the qualified key tells
        // them apart, and that is the spelling `opcfamily` uses.
        let families = parse_dat(
            "[{ oid => '397', opfmethod => 'btree', opfname => 'array_ops' },\n\
              { oid => '627', opfmethod => 'hash', opfname => 'array_ops' }]",
        );
        let mut symbols = SymbolTable::default();
        define_symbols(&families, &mut symbols);
        assert_eq!(symbols.resolve_name(Opfamily, "btree/array_ops"), Some(397));
        assert_eq!(symbols.resolve_name(Opfamily, "hash/array_ops"), Some(627));

        let emitted = emit(&families, &symbols);
        assert!(emitted.contains(
            "PgOpfamilyRow { oid: 397, opfmethod: 403, opfname: \"array_ops\" },\n    \
             PgOpfamilyRow { oid: 627, opfmethod: 405, opfname: \"array_ops\" },"
        ));
    }
}
