//! `PG_OPERATOR_ROWS` codegen.
//!
//! An operator is referenced by signature and never by name — `=` names some
//! ninety of them — so [`define_symbols`] is what lets `pg_amop.amopopr`, this
//! catalog's own `oprcom`/`oprnegate` and `pg_aggregate.aggsortop` resolve.
//! Those self-references are the reference cycle the two phases exist for: an
//! operator's commutator is an operator.
//!
//! Every entry carries an `oid`, so nothing here is numbered.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, get, oid_field, str_field};
use crate::symbols::SymbolKind::{Operator, Type};
use crate::symbols::SymbolTable;

/// The signature an operator is referenced by: `oprname(oprleft,oprright)`.
///
/// A prefix operator writes its absent left operand as the type `0`, which
/// travels into the key as written — see [`SymbolKind::Operator`].
pub fn signature(e: &Entry) -> (String, String) {
    let name = get(e, "oprname")
        .unwrap_or_else(|| panic!("pg_operator entry without oprname"))
        .to_string();
    let operands = format!(
        "{},{}",
        str_field(e, "oprleft", "0"),
        str_field(e, "oprright", "0")
    );
    (name, operands)
}

/// Phase one: every operator, under the `name(left,right)` spelling
/// `pg_amop.amopopr`, `pg_aggregate.aggsortop` and this catalog's own
/// `oprcom`/`oprnegate` reference it by.
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        let (name, operands) = signature(e);
        symbols.define_signature(Operator, &name, &operands, oid_field(e, "oid"));
    }
}

/// Emit `PG_OPERATOR_ROWS: &[PgOperatorRow]` from `pg_operator.dat`, in file
/// order — the order upstream inserts the rows in, and so the order a client
/// reading the relation without `ORDER BY` sees them.
///
/// Every entry is emitted. What this build's expression resolver actually
/// evaluates is a fraction of them, and that divergence is stated where it is
/// observable rather than papered over by shortening the list: see
/// `crabgresql-catalog`'s `catalogs::operator`.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let type_oid = |name: &str| match name {
        // A prefix operator writes its absent operand as the type `0`, which
        // is PostgreSQL's "no such object" and stays 0 in the column.
        "0" => 0,
        name => symbols.resolve_name(Type, name).unwrap_or_else(|| {
            panic!("pg_operator references type {name:?}, which pg_type.dat lacks")
        }),
    };
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_operator.dat\n");
    out.push_str("pub static PG_OPERATOR_ROWS: &[PgOperatorRow] = &[\n");
    for e in entries {
        let oid = oid_field(e, "oid");
        let oprname = str_field(e, "oprname", "");
        let _ = writeln!(
            out,
            "    PgOperatorRow {{ oid: {oid}, oprname: {oprname:?}, oprkind: {oprkind:?}, \
oprcanmerge: {canmerge}, oprcanhash: {canhash}, oprleft: {left}, oprright: {right}, \
oprresult: {result}, oprcom: {com}, oprnegate: {negate}, oprcode: {code}, \
oprrest: {rest}, oprjoin: {join} }},",
            // `b` is an infix operator, the BKI default; `l` is a prefix one,
            // whose left operand the data writes as `0`.
            oprkind = str_field(e, "oprkind", "b"),
            canmerge = bool_field(e, "oprcanmerge", false),
            canhash = bool_field(e, "oprcanhash", false),
            left = type_oid(str_field(e, "oprleft", "0")),
            right = type_oid(str_field(e, "oprright", "0")),
            result = type_oid(str_field(e, "oprresult", "0")),
            // The commutator and negator are operators, and an entry may name
            // one that appears later in the file — resolved rather than
            // ordered, which is what phase two buys. Absent means there is
            // none, which PostgreSQL stores as 0.
            com = operator_oid(symbols, get(e, "oprcom"), oprname, "oprcom"),
            negate = operator_oid(symbols, get(e, "oprnegate"), oprname, "oprnegate"),
            // `oprcode` is the function that evaluates the operator and must
            // resolve; the two selectivity estimators may be absent, which the
            // catalog spells `-`.
            code = code_ref(symbols, e, oprname),
            rest = crate::proc_ref(symbols, str_field(e, "oprrest", "-")),
            join = crate::proc_ref(symbols, str_field(e, "oprjoin", "-")),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

/// The OID a `oprcom`/`oprnegate` reference names, or 0 when there is none.
fn operator_oid(symbols: &SymbolTable, reference: Option<&str>, of: &str, column: &str) -> u32 {
    let Some(reference) = reference else {
        return 0;
    };
    symbols
        .resolve_signature(Operator, reference)
        .unwrap_or_else(|| {
            panic!("pg_operator {of}: {column} {reference:?} names no pg_operator entry")
        })
}

/// The `ProcRef` an entry's `oprcode` names. Unlike the estimators, this one
/// cannot be `-`: an operator with no implementation is not an operator, so a
/// reference that fails to resolve fails the build rather than emitting a row
/// that claims `=` is evaluated by nothing.
fn code_ref(symbols: &SymbolTable, e: &Entry, oprname: &str) -> String {
    let reference = str_field(e, "oprcode", "");
    crate::proc_ref_resolved(symbols, reference).unwrap_or_else(|| {
        panic!("pg_operator {oprname}: oprcode {reference:?} names no pg_proc entry")
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    #[test]
    fn an_operator_is_keyed_by_its_operands() {
        // `=` names ninety-odd operators; only the operand types tell them
        // apart, and that is the spelling every reference uses.
        let ops = parse_dat(
            "[{ oid => '15', oprname => '=', oprleft => 'int4', oprright => 'int8' },\n\
              { oid => '410', oprname => '=', oprleft => 'int8', oprright => 'int8' },\n\
              { oid => '484', oprname => '-', oprkind => 'l', oprleft => '0', \
             oprright => 'int8' }]",
        );
        let mut symbols = SymbolTable::default();
        define_symbols(&ops, &mut symbols);
        assert_eq!(
            symbols.resolve_signature(Operator, "=(int4,int8)"),
            Some(15)
        );
        assert_eq!(
            symbols.resolve_signature(Operator, "=(int8,int8)"),
            Some(410)
        );
        // A prefix operator keys off the `0` its data writes, so a reference
        // to one resolves rather than dangling.
        assert_eq!(symbols.resolve_signature(Operator, "-(0,int8)"), Some(484));
        assert_eq!(symbols.resolve_signature(Operator, "=(int4,int4)"), None);
    }

    /// The selectivity estimators are the one pair of `regproc` columns an
    /// entry may leave out, so they are where the difference between "the
    /// catalog says there is none" and "the name did not resolve" is visible.
    fn emit_one(dat: &str) -> String {
        let ops = parse_dat(dat);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Type, "bool", 16);
        crate::pg_proc::define_symbols(
            &parse_dat(
                "[{ oid => '65', proname => 'int4eq', proargtypes => 'int4 int4' },\n\
                  { oid => '101', proname => 'eqsel', proargtypes => 'internal' }]",
            ),
            &mut symbols,
        );
        define_symbols(&ops, &mut symbols);
        emit(&ops, &symbols)
    }

    #[test]
    fn an_absent_estimator_is_the_catalogs_none() {
        let emitted = emit_one(
            "[{ oid => '96', oprname => '=', oprleft => 'int4', oprright => 'int4', \
             oprresult => 'bool', oprcode => 'int4eq', oprrest => 'eqsel' }]",
        );
        assert!(emitted.contains("oprrest: ProcRef { oid: 101, name: \"eqsel\" }"));
        // `oprjoin` is absent, and absent is the only thing that reads as 0.
        assert!(emitted.contains("oprjoin: ProcRef { oid: 0, name: \"-\" }"));
    }

    #[test]
    #[should_panic(expected = "names no pg_proc entry")]
    fn an_unresolvable_estimator_fails_the_build() {
        // Before this, the row was emitted as `ProcRef { oid: 0, name:
        // "nosuchsel" }` — a column naming a function and pointing at nothing,
        // which no test and no reader would have questioned.
        emit_one(
            "[{ oid => '96', oprname => '=', oprleft => 'int4', oprright => 'int4', \
             oprresult => 'bool', oprcode => 'int4eq', oprrest => 'nosuchsel' }]",
        );
    }
}
