//! `PG_OPCLASS_ROWS` codegen.
//!
//! Only 13 of the 179 entries spell an `oid` out; the rest are numbered by
//! [`OidCounter`], whose docs carry the rule and how it was checked.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, get, str_field};
use crate::symbols::SymbolKind::{Opfamily, Type};
use crate::symbols::SymbolTable;
use crate::{OidCounter, am_oid};

/// Emit `PG_OPCLASS_ROWS: &[PgOpclassRow]` from `pg_opclass.dat`, in file
/// order — the order upstream inserts the rows in, and so the order a client
/// reading the relation without `ORDER BY` sees them.
///
/// Every entry is emitted, including the classes for access methods this build
/// has no index for (`gist`, `gin`, `spgist`, `brin`). `pg_am` already lists
/// those methods, and an opclass row is a statement about what the *type* can
/// be indexed by rather than a promise that this server will build the index.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let type_oid = |name: &str| {
        symbols.resolve_name(Type, name).unwrap_or_else(|| {
            panic!("pg_opclass references type {name:?}, which pg_type.dat lacks")
        })
    };
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_opclass.dat\n");
    out.push_str("pub static PG_OPCLASS_ROWS: &[PgOpclassRow] = &[\n");
    let mut oids = OidCounter::default();
    for e in entries {
        let opcname = str_field(e, "opcname", "");
        let oid = oids.of(e);
        let family = str_field(e, "opcfamily", "");
        let _ = writeln!(
            out,
            "    PgOpclassRow {{ oid: {oid}, opcmethod: {method}, opcname: {opcname:?}, \
opcfamily: {opcfamily}, opcintype: {opcintype}, opcdefault: {opcdefault}, \
opckeytype: {opckeytype} }},",
            method = am_oid(str_field(e, "opcmethod", "")),
            opcfamily = symbols
                .resolve_name(Opfamily, family)
                .unwrap_or_else(|| panic!(
                    "pg_opclass {opcname}: opcfamily {family:?} names no pg_opfamily entry"
                )),
            opcintype = type_oid(str_field(e, "opcintype", "")),
            opcdefault = bool_field(e, "opcdefault", true),
            opckeytype = get(e, "opckeytype").map_or(0, type_oid),
        );
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    fn symbols() -> SymbolTable {
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "int4", 23);
        symbols.define_name(Type, "int2", 21);
        symbols.define_name(Type, "text", 25);
        symbols.define_name(Opfamily, "btree/integer_ops", 1976);
        symbols.define_name(Opfamily, "btree/text_ops", 1994);
        symbols
    }

    #[test]
    fn an_explicit_oid_does_not_spend_a_generated_one() {
        // The shape the real file has: a numbered entry between two unnumbered
        // ones. If the counter advanced past the explicit entry, every OID
        // after it would be one too high; if the explicit OID reset it, they
        // would collide.
        let classes = parse_dat(
            "[{ opcmethod => 'btree', opcname => 'int2_ops', \
             opcfamily => 'btree/integer_ops', opcintype => 'int2' },\n\
              { oid => '1978', opcmethod => 'btree', opcname => 'int4_ops', \
             opcfamily => 'btree/integer_ops', opcintype => 'int4' },\n\
              { opcmethod => 'btree', opcname => 'text_ops', \
             opcfamily => 'btree/text_ops', opcintype => 'text' }]",
        );
        let emitted = emit(&classes, &symbols());
        assert!(emitted.contains("oid: 10000, opcmethod: 403, opcname: \"int2_ops\""));
        assert!(emitted.contains("oid: 1978, opcmethod: 403, opcname: \"int4_ops\""));
        assert!(emitted.contains("oid: 10001, opcmethod: 403, opcname: \"text_ops\""));
    }

    #[test]
    fn defaults_fill_the_columns_the_dat_omits() {
        let classes = parse_dat(
            "[{ opcmethod => 'btree', opcname => 'int4_ops', \
             opcfamily => 'btree/integer_ops', opcintype => 'int4' }]",
        );
        let emitted = emit(&classes, &symbols());
        // An entry that says nothing is its type's default class, storing that
        // type itself.
        assert!(emitted.contains("opcdefault: true"));
        assert!(emitted.contains("opckeytype: 0"));
    }

    #[test]
    #[should_panic(expected = "names no pg_opfamily entry")]
    fn an_unresolvable_family_fails_the_build() {
        let classes = parse_dat(
            "[{ opcmethod => 'btree', opcname => 'int4_ops', \
             opcfamily => 'btree/nosuch_ops', opcintype => 'int4' }]",
        );
        emit(&classes, &symbols());
    }
}
