//! `PG_PROC_ROWS` codegen.

use std::fmt::Write as _;

use crate::dat::{Entry, array_field, bool_field, braced_list_len, get, oid_field, str_field};
use crate::implemented::IMPLEMENTED_PRONAMES;
use crate::symbols::SymbolKind::{Proc, Type};
use crate::symbols::SymbolTable;

/// What [`emit`] produces: the generated source, and the OIDs it published.
///
/// The published set is wider than the reference census, so `pg_description`
/// cannot reuse the census to decide which `pg_proc` comments to keep — a
/// comment on a row this build publishes belongs in the catalog, and one on a
/// row it does not would describe nothing.
pub struct Emitted {
    pub code: String,
    /// Ascending, as `pg_description`'s filter expects.
    pub published: Vec<u32>,
}

/// A generated array literal's elements, comma-separated. An absent field
/// yields no elements, which the emitted row spells as an empty slice.
///
/// An entry writing `{}` is refused rather than emitted. PostgreSQL means "an
/// array with no elements" by it, the generated rows spell NULL as an empty
/// slice, and [`crate::dat::array_field`] keeps the two apart — but only up to
/// here, since `crabgresql-catalog`'s `cols::optional_array` renders an empty
/// slice as NULL. No entry in the vendored data writes one, so refusing is the
/// same trade the `proargdefaults` check below makes: reject data codegen
/// cannot represent instead of quietly representing it as something else.
fn list(e: &Entry, key: &str, render: impl Fn(&str) -> String) -> String {
    let Some(values) = array_field(e, key) else {
        return String::new();
    };
    assert!(
        !values.is_empty(),
        "pg_proc entry {}: {key} is an empty array, which codegen cannot tell \
         from NULL",
        str_field(e, "proname", "")
    );
    values
        .iter()
        .map(|v| render(v))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Every name the manifest claims is defined by `pg_proc.dat`. A name that is
/// not is a typo, or a function upstream has renamed: either way the claim can
/// publish no row, so say so rather than emit nothing.
///
/// Runs over the real data from [`crate::generate`], not from [`emit`], so a
/// test may emit any fixture it likes.
pub fn check_manifest(entries: &[Entry]) {
    for name in IMPLEMENTED_PRONAMES {
        assert!(
            entries.iter().any(|e| get(e, "proname") == Some(name)),
            "IMPLEMENTED_PRONAMES lists {name:?}, which pg_proc.dat defines no entry for"
        );
    }
}

/// Phase one: every function `pg_proc.dat` defines, under both spellings the
/// other catalogs reference it by — bare name (`regproc`, as
/// `pg_type.typinput` writes it) and full signature (`regprocedure`, as
/// `pg_cast.castfunc` writes it).
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        let Some(name) = get(e, "proname") else {
            continue;
        };
        let oid = oid_field(e, "oid");
        symbols.define_name(Proc, name, oid);
        symbols.define_signature(Proc, name, str_field(e, "proargtypes", ""), oid);
    }
}

/// Emit `PG_PROC_ROWS: &[PgProcRow]`, plus the OIDs it published — the census
/// `pg_description` filters its `pg_proc` comments by.
///
/// A `pg_proc` row is a claim that the function exists, so every row needs a
/// justification and there are exactly two:
///
///   - an **inbound reference** from a catalog emitted before this one
///     ([`SymbolTable::references`] is that census) — which would otherwise
///     dangle, and is why this catalog is emitted **last** and why the census
///     seals itself when read;
///   - the binder **implements the name**
///     ([`crate::implemented::IMPLEMENTED_PRONAMES`]) — the SQL surface no
///     vendored reference points at.
///
/// The rest of `pg_proc.dat` stays out: this build serves its own function
/// registry, not upstream's list.
///
/// Omitted fields fall back to PostgreSQL's `pg_proc` BKI defaults (authored
/// from the public catalog docs and checked against a running 18.4).
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> Emitted {
    let referenced = symbols.references(Proc);
    let type_oid = |name: &str| {
        symbols
            .resolve_name(Type, name)
            .unwrap_or_else(|| panic!("pg_proc references type {name:?}, which pg_type.dat lacks"))
    };
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_proc.dat\n");
    out.push_str("pub static PG_PROC_ROWS: &[PgProcRow] = &[\n");
    let mut rows: Vec<(u32, String)> = Vec::new();
    for e in entries {
        let oid = oid_field(e, "oid");
        let proname = str_field(e, "proname", "");
        if referenced.binary_search(&oid).is_err()
            && IMPLEMENTED_PRONAMES.binary_search(&proname).is_err()
        {
            continue;
        }
        // `pronargdefaults` is derived, never written: PostgreSQL counts the
        // `proargdefaults` list rather than storing the count twice, so an entry
        // spelling it out would be data this codegen does not read.
        assert!(
            get(e, "pronargdefaults").is_none(),
            "pg_proc entry {proname} carries pronargdefaults, which codegen derives"
        );
        let argtypes: Vec<u32> = str_field(e, "proargtypes", "")
            .split_whitespace()
            .map(type_oid)
            .collect();
        let retset = bool_field(e, "proretset", false);
        let args = argtypes
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let row = format!(
            "    PgProcRow {{ oid: {oid}, proname: {proname:?}, prolang: {prolang}, \
procost: {procost:?}, prorows: {prorows:?}, provariadic: {provariadic}, \
prosupport: {prosupport}, prokind: {prokind:?}, prosecdef: false, \
proleakproof: {proleakproof}, proisstrict: {proisstrict}, proretset: {retset}, \
provolatile: {provolatile:?}, proparallel: {proparallel:?}, pronargs: {pronargs}, \
pronargdefaults: {pronargdefaults}, \
prorettype: {prorettype}, proargtypes: &[{args}], proallargtypes: &[{allargs}], \
proargmodes: &[{argmodes}], proargnames: &[{argnames}], prosrc: {prosrc:?}, \
probin: {probin:?} }},\n",
            prolang = match str_field(e, "prolang", "internal") {
                "c" => 13,
                "sql" => 14,
                other => {
                    assert_eq!(other, "internal", "unknown prolang {other:?}");
                    12
                }
            },
            procost = str_field(e, "procost", "1")
                .parse::<f32>()
                .unwrap_or_else(|_| panic!("bad procost on {proname}")),
            // A set-returning function with no explicit estimate reports
            // PostgreSQL's 1000-row planner default; a scalar one reports 0.
            prorows = match get(e, "prorows") {
                Some(rows) => rows
                    .parse::<f32>()
                    .unwrap_or_else(|_| panic!("bad prorows on {proname}")),
                None if retset => 1000.0,
                None => 0.0,
            },
            provariadic = get(e, "provariadic").map_or(0, type_oid),
            // A planner support routine is itself a `pg_proc` row this codegen
            // does not emit, so pointing at one would dangle. Report none —
            // which is also true of what the planner here actually consults.
            prosupport = crate::proc_ref(symbols, "-"),
            prokind = str_field(e, "prokind", "f"),
            proleakproof = bool_field(e, "proleakproof", false),
            proisstrict = bool_field(e, "proisstrict", true),
            provolatile = str_field(e, "provolatile", "i"),
            proparallel = str_field(e, "proparallel", "s"),
            pronargs = argtypes.len(),
            // How many trailing arguments a call may omit. The default
            // *expressions* are not carried: `pg_proc` here publishes no
            // `proargdefaults` column, so there is nothing to render them from
            // — but the count is what a client reads to know the minimum arity,
            // and reporting 0 would claim `make_interval()` needs seven
            // arguments.
            pronargdefaults = braced_list_len(e, "proargdefaults").unwrap_or(0),
            prorettype = type_oid(str_field(e, "prorettype", "")),
            // The three OUT-parameter columns. PostgreSQL leaves all three NULL
            // unless a function has OUT or VARIADIC parameters, and an empty
            // slice is how the generated rows spell that NULL — see
            // `crabgresql-catalog`'s `PgProcRow`. A function that declares any
            // of them declares `proallargtypes` and `proargmodes` together;
            // `proargnames` travels on its own, since a function may name plain
            // IN arguments.
            allargs = list(e, "proallargtypes", |t| type_oid(t).to_string()),
            argmodes = list(e, "proargmodes", |m| format!("{m:?}")),
            argnames = list(e, "proargnames", |n| format!("{n:?}")),
            prosrc = str_field(e, "prosrc", ""),
            // The shared library a conversion or other C function lives in.
            // Empty for the internal functions, which is what the catalog
            // reports as NULL.
            probin = str_field(e, "probin", ""),
        );
        rows.push((oid, row));
    }
    rows.sort_by_key(|(oid, _)| *oid);
    for (_, row) in &rows {
        out.push_str(row);
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    Emitted {
        code: out,
        published: rows.iter().map(|(oid, _)| *oid).collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    const PROCS: &str = "[{ oid => '1242', proname => 'boolin', prorettype => 'bool', \
         proargtypes => 'cstring', provolatile => 'i' },\n\
          { oid => '1243', proname => 'boolout', prorettype => 'cstring', \
         proargtypes => 'bool' }]";

    /// The generated source alone: every test below reads the code, not the
    /// published census.
    fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
        super::emit(entries, symbols).code
    }

    fn fixture() -> (Vec<Entry>, SymbolTable) {
        let procs = parse_dat(PROCS);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        (procs, symbols)
    }

    #[test]
    fn emits_only_the_functions_something_points_at() {
        let (procs, symbols) = fixture();
        symbols.resolve_name(Proc, "boolin");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("proname: \"boolin\""));
        assert!(!emitted.contains("proname: \"boolout\""));
        // Argument and return types resolve even though `pg_type` referenced
        // this function first — that is the point of the two phases.
        assert!(emitted.contains("prorettype: 16"));
        assert!(emitted.contains("proargtypes: &[2275]"));
        assert!(emitted.contains("pronargs: 1"));
    }

    /// The second justification for a row: nothing references the entry, but
    /// the binder resolves the name, so a client can find it. `booleq` is in
    /// the manifest and `boolout` is not, which is the whole difference here.
    #[test]
    fn emits_the_functions_this_build_implements() {
        let procs = parse_dat(
            "[{ oid => '60', proname => 'booleq', prorettype => 'bool', \
             proargtypes => 'bool bool' },\n\
              { oid => '1243', proname => 'boolout', prorettype => 'cstring', \
             proargtypes => 'bool' }]",
        );
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        assert!(IMPLEMENTED_PRONAMES.binary_search(&"booleq").is_ok());
        assert!(IMPLEMENTED_PRONAMES.binary_search(&"boolout").is_err());
        let emitted = super::emit(&procs, &symbols);
        assert!(emitted.code.contains("proname: \"booleq\""));
        assert!(!emitted.code.contains("proname: \"boolout\""));
        // The published census is what `pg_description` keeps its comments by,
        // so it must carry the implemented row too, not only referenced ones.
        assert_eq!(emitted.published, vec![60]);
    }

    /// A manifest name upstream does not define cannot publish a row, so
    /// codegen refuses the build rather than emit nothing.
    #[test]
    #[should_panic(expected = "which pg_proc.dat defines no entry for")]
    fn a_manifest_name_the_dat_lacks_fails_the_build() {
        check_manifest(&parse_dat("[{ oid => '1', proname => 'f' }]"));
    }

    #[test]
    fn defaults_fill_the_columns_the_dat_omits() {
        let (procs, symbols) = fixture();
        symbols.resolve_signature(Proc, "boolout(bool)");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("prolang: 12")); // internal
        assert!(emitted.contains("procost: 1.0"));
        assert!(emitted.contains("prorows: 0.0")); // not set-returning
        assert!(emitted.contains("proisstrict: true"));
        assert!(emitted.contains("provolatile: \"i\""));
        assert!(emitted.contains("prokind: \"f\""));
    }

    /// Emit one entry, whatever it says, resolved against `bool`/`cstring`.
    fn emit_one(dat: &str) -> String {
        let procs = parse_dat(dat);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        symbols.resolve_name(Proc, "f");
        emit(&procs, &symbols)
    }

    #[test]
    fn a_function_without_out_parameters_reports_the_three_columns_empty() {
        let (procs, symbols) = fixture();
        symbols.resolve_name(Proc, "boolin");
        let emitted = emit(&procs, &symbols);
        // Empty is the generated spelling of NULL, which is what PostgreSQL
        // stores for a function that declares neither OUT parameters nor
        // argument names.
        assert!(emitted.contains("proallargtypes: &[], proargmodes: &[], proargnames: &[]"));
        assert!(emitted.contains("probin: \"\""));
    }

    #[test]
    fn out_parameters_and_argument_names_are_emitted() {
        let emitted = emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargtypes => 'cstring', proallargtypes => '{cstring,bool}', \
             proargmodes => '{i,o}', proargnames => '{arg,found}', \
             probin => '$libdir/thing' }]",
        );
        assert!(emitted.contains("proallargtypes: &[2275, 16]"));
        assert!(emitted.contains("proargmodes: &[\"i\", \"o\"]"));
        assert!(emitted.contains("proargnames: &[\"arg\", \"found\"]"));
        assert!(emitted.contains("probin: \"$libdir/thing\""));
        // `pronargs` still counts the declared arguments, not the OUT ones.
        assert!(emitted.contains("pronargs: 1"));
    }

    #[test]
    #[should_panic(expected = "codegen cannot tell from NULL")]
    fn an_empty_array_column_is_refused() {
        // `{}` is an array with no elements and `_null_` is no array at all;
        // the generated rows spell only the second, so the first is refused
        // rather than silently reported as NULL.
        emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargnames => '{}' }]",
        );
    }

    /// An argument default is counted, not read: `pronargdefaults` is how many
    /// trailing arguments a call may omit, and the expressions themselves have
    /// no column to live in here. A quoted element carrying a comma (as
    /// `jsonb_path_exists`'s `'{"{}",false}'` does) is still one default.
    #[test]
    fn argument_defaults_are_counted() {
        let emitted = emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargtypes => 'bool bool', proargdefaults => '{\"{}\",false}' }]",
        );
        assert!(emitted.contains("pronargs: 2, pronargdefaults: 2"));
    }

    /// `pronargdefaults` is derived from that list, so an entry spelling it out
    /// would be data codegen ignores.
    #[test]
    #[should_panic(expected = "carries pronargdefaults, which codegen derives")]
    fn a_spelled_out_default_count_is_refused() {
        emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             pronargdefaults => '1' }]",
        );
    }
}
