//! `PG_PROC_ROWS` codegen.

use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, get, oid_field, str_field};
use crate::symbols::SymbolKind::{Proc, Type};
use crate::symbols::SymbolTable;

/// Phase one: every function `pg_proc.dat` defines, under both spellings the
/// other catalogs reference it by — bare name (`regproc`, as
/// `pg_type.typinput` writes it) and full signature (`regprocedure`, as
/// `pg_cast.castfunc` writes it).
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        let Some(name) = get(e, "proname") else {
            continue;
        };
        let oid = oid_field(e, "oid");
        symbols.define_name(Proc, name, oid);
        symbols.define_signature(Proc, name, str_field(e, "proargtypes", ""), oid);
    }
}

/// Emit `PG_PROC_ROWS: &[PgProcRow]` for the functions the catalogs emitted
/// before this one point at — [`SymbolTable::references`] is that census. The
/// rest of `pg_proc.dat` is deliberately left out: a `pg_proc` row is a claim
/// that the function exists, and this build implements its SQL surface from its
/// own registry, not from upstream's list. Every row emitted here is justified
/// by an inbound reference that would otherwise dangle — which is why this
/// catalog must be emitted **last**, and why the census seals itself when read.
///
/// Omitted fields fall back to PostgreSQL's `pg_proc` BKI defaults (authored
/// from the public catalog docs and checked against a running 18.4).
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let referenced = symbols.references(Proc);
    let type_oid = |name: &str| {
        symbols
            .resolve_name(Type, name)
            .unwrap_or_else(|| panic!("pg_proc references type {name:?}, which pg_type.dat lacks"))
    };
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_proc.dat\n");
    out.push_str("pub static PG_PROC_ROWS: &[PgProcRow] = &[\n");
    let mut rows: Vec<(u32, String)> = Vec::new();
    for e in entries {
        let oid = oid_field(e, "oid");
        if referenced.binary_search(&oid).is_err() {
            continue;
        }
        let proname = str_field(e, "proname", "");
        // The emitted subset is I/O, cast and handler functions, none of which
        // take OUT parameters or defaults. Anything else would need those
        // columns filled rather than left NULL, so refuse rather than lie.
        for unsupported in [
            "proallargtypes",
            "proargmodes",
            "proargnames",
            "proargdefaults",
        ] {
            assert!(
                get(e, unsupported).is_none(),
                "pg_proc entry {proname} carries {unsupported}, which codegen does not emit"
            );
        }
        let argtypes: Vec<u32> = str_field(e, "proargtypes", "")
            .split_whitespace()
            .map(type_oid)
            .collect();
        let retset = bool_field(e, "proretset", false);
        let args = argtypes
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let row = format!(
            "    PgProcRow {{ oid: {oid}, proname: {proname:?}, prolang: {prolang}, \
procost: {procost:?}, prorows: {prorows:?}, provariadic: {provariadic}, \
prosupport: {prosupport}, prokind: {prokind:?}, prosecdef: false, \
proleakproof: {proleakproof}, proisstrict: {proisstrict}, proretset: {retset}, \
provolatile: {provolatile:?}, proparallel: {proparallel:?}, pronargs: {pronargs}, \
prorettype: {prorettype}, proargtypes: &[{args}], prosrc: {prosrc:?} }},\n",
            prolang = match str_field(e, "prolang", "internal") {
                "c" => 13,
                "sql" => 14,
                other => {
                    assert_eq!(other, "internal", "unknown prolang {other:?}");
                    12
                }
            },
            procost = str_field(e, "procost", "1")
                .parse::<f32>()
                .unwrap_or_else(|_| panic!("bad procost on {proname}")),
            // A set-returning function with no explicit estimate reports
            // PostgreSQL's 1000-row planner default; a scalar one reports 0.
            prorows = match get(e, "prorows") {
                Some(rows) => rows
                    .parse::<f32>()
                    .unwrap_or_else(|_| panic!("bad prorows on {proname}")),
                None if retset => 1000.0,
                None => 0.0,
            },
            provariadic = get(e, "provariadic").map_or(0, type_oid),
            // A planner support routine is itself a `pg_proc` row this codegen
            // does not emit, so pointing at one would dangle. Report none —
            // which is also true of what the planner here actually consults.
            prosupport = crate::proc_ref(symbols, "-"),
            prokind = str_field(e, "prokind", "f"),
            proleakproof = bool_field(e, "proleakproof", false),
            proisstrict = bool_field(e, "proisstrict", true),
            provolatile = str_field(e, "provolatile", "i"),
            proparallel = str_field(e, "proparallel", "s"),
            pronargs = argtypes.len(),
            prorettype = type_oid(str_field(e, "prorettype", "")),
            prosrc = str_field(e, "prosrc", ""),
        );
        rows.push((oid, row));
    }
    rows.sort_by_key(|(oid, _)| *oid);
    for (_, row) in &rows {
        out.push_str(row);
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    const PROCS: &str = "[{ oid => '1242', proname => 'boolin', prorettype => 'bool', \
         proargtypes => 'cstring', provolatile => 'i' },\n\
          { oid => '1243', proname => 'boolout', prorettype => 'cstring', \
         proargtypes => 'bool' }]";

    fn fixture() -> (Vec<Entry>, SymbolTable) {
        let procs = parse_dat(PROCS);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        (procs, symbols)
    }

    #[test]
    fn emits_only_the_functions_something_points_at() {
        let (procs, symbols) = fixture();
        symbols.resolve_name(Proc, "boolin");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("proname: \"boolin\""));
        assert!(!emitted.contains("proname: \"boolout\""));
        // Argument and return types resolve even though `pg_type` referenced
        // this function first — that is the point of the two phases.
        assert!(emitted.contains("prorettype: 16"));
        assert!(emitted.contains("proargtypes: &[2275]"));
        assert!(emitted.contains("pronargs: 1"));
    }

    #[test]
    fn defaults_fill_the_columns_the_dat_omits() {
        let (procs, symbols) = fixture();
        symbols.resolve_signature(Proc, "boolout(bool)");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("prolang: 12")); // internal
        assert!(emitted.contains("procost: 1.0"));
        assert!(emitted.contains("prorows: 0.0")); // not set-returning
        assert!(emitted.contains("proisstrict: true"));
        assert!(emitted.contains("provolatile: \"i\""));
        assert!(emitted.contains("prokind: \"f\""));
    }

    #[test]
    #[should_panic(expected = "which codegen does not emit")]
    fn a_function_with_out_parameters_is_refused() {
        let procs = parse_dat(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargnames => '{a}' }]",
        );
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        define_symbols(&procs, &mut symbols);
        symbols.resolve_name(Proc, "f");
        emit(&procs, &symbols);
    }
}
