//! `PG_PROC_ROWS` codegen.

use std::fmt::Write as _;

use crate::dat::{Entry, array_field, bool_field, get, oid_field, str_field};
use crate::symbols::SymbolKind::{Proc, Type};
use crate::symbols::SymbolTable;

/// A generated array literal's elements, comma-separated. An absent field
/// yields no elements, which the emitted row spells as an empty slice.
fn list(values: Option<Vec<String>>, render: impl Fn(&str) -> String) -> String {
    values
        .unwrap_or_default()
        .iter()
        .map(|v| render(v))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Phase one: every function `pg_proc.dat` defines, under both spellings the
/// other catalogs reference it by — bare name (`regproc`, as
/// `pg_type.typinput` writes it) and full signature (`regprocedure`, as
/// `pg_cast.castfunc` writes it).
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        let Some(name) = get(e, "proname") else {
            continue;
        };
        let oid = oid_field(e, "oid");
        symbols.define_name(Proc, name, oid);
        symbols.define_signature(Proc, name, str_field(e, "proargtypes", ""), oid);
    }
}

/// Emit `PG_PROC_ROWS: &[PgProcRow]` for the functions the catalogs emitted
/// before this one point at — [`SymbolTable::references`] is that census. The
/// rest of `pg_proc.dat` is deliberately left out: a `pg_proc` row is a claim
/// that the function exists, and this build implements its SQL surface from its
/// own registry, not from upstream's list. Every row emitted here is justified
/// by an inbound reference that would otherwise dangle — which is why this
/// catalog must be emitted **last**, and why the census seals itself when read.
///
/// Omitted fields fall back to PostgreSQL's `pg_proc` BKI defaults (authored
/// from the public catalog docs and checked against a running 18.4).
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let referenced = symbols.references(Proc);
    let type_oid = |name: &str| {
        symbols
            .resolve_name(Type, name)
            .unwrap_or_else(|| panic!("pg_proc references type {name:?}, which pg_type.dat lacks"))
    };
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_proc.dat\n");
    out.push_str("pub static PG_PROC_ROWS: &[PgProcRow] = &[\n");
    let mut rows: Vec<(u32, String)> = Vec::new();
    for e in entries {
        let oid = oid_field(e, "oid");
        if referenced.binary_search(&oid).is_err() {
            continue;
        }
        let proname = str_field(e, "proname", "");
        // An argument default is a serialized expression tree, and nothing here
        // can render one: `pg_get_function_arguments` would have to print the
        // expression back. No function the catalogs reference carries one, so
        // refusing is exact rather than restrictive — and `pronargdefaults`
        // stays 0 for the same reason.
        for unsupported in ["proargdefaults", "pronargdefaults"] {
            assert!(
                get(e, unsupported).is_none(),
                "pg_proc entry {proname} carries {unsupported}, which codegen does not emit"
            );
        }
        let argtypes: Vec<u32> = str_field(e, "proargtypes", "")
            .split_whitespace()
            .map(type_oid)
            .collect();
        let retset = bool_field(e, "proretset", false);
        let args = argtypes
            .iter()
            .map(u32::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let row = format!(
            "    PgProcRow {{ oid: {oid}, proname: {proname:?}, prolang: {prolang}, \
procost: {procost:?}, prorows: {prorows:?}, provariadic: {provariadic}, \
prosupport: {prosupport}, prokind: {prokind:?}, prosecdef: false, \
proleakproof: {proleakproof}, proisstrict: {proisstrict}, proretset: {retset}, \
provolatile: {provolatile:?}, proparallel: {proparallel:?}, pronargs: {pronargs}, \
prorettype: {prorettype}, proargtypes: &[{args}], proallargtypes: &[{allargs}], \
proargmodes: &[{argmodes}], proargnames: &[{argnames}], prosrc: {prosrc:?}, \
probin: {probin:?} }},\n",
            prolang = match str_field(e, "prolang", "internal") {
                "c" => 13,
                "sql" => 14,
                other => {
                    assert_eq!(other, "internal", "unknown prolang {other:?}");
                    12
                }
            },
            procost = str_field(e, "procost", "1")
                .parse::<f32>()
                .unwrap_or_else(|_| panic!("bad procost on {proname}")),
            // A set-returning function with no explicit estimate reports
            // PostgreSQL's 1000-row planner default; a scalar one reports 0.
            prorows = match get(e, "prorows") {
                Some(rows) => rows
                    .parse::<f32>()
                    .unwrap_or_else(|_| panic!("bad prorows on {proname}")),
                None if retset => 1000.0,
                None => 0.0,
            },
            provariadic = get(e, "provariadic").map_or(0, type_oid),
            // A planner support routine is itself a `pg_proc` row this codegen
            // does not emit, so pointing at one would dangle. Report none —
            // which is also true of what the planner here actually consults.
            prosupport = crate::proc_ref(symbols, "-"),
            prokind = str_field(e, "prokind", "f"),
            proleakproof = bool_field(e, "proleakproof", false),
            proisstrict = bool_field(e, "proisstrict", true),
            provolatile = str_field(e, "provolatile", "i"),
            proparallel = str_field(e, "proparallel", "s"),
            pronargs = argtypes.len(),
            prorettype = type_oid(str_field(e, "prorettype", "")),
            // The three OUT-parameter columns. PostgreSQL leaves all three NULL
            // unless a function has OUT or VARIADIC parameters, and an empty
            // slice is how the generated rows spell that NULL — see
            // `crabgresql-catalog`'s `PgProcRow`. A function that declares any
            // of them declares `proallargtypes` and `proargmodes` together;
            // `proargnames` travels on its own, since a function may name plain
            // IN arguments.
            allargs = list(array_field(e, "proallargtypes"), |t| type_oid(t)
                .to_string()),
            argmodes = list(array_field(e, "proargmodes"), |m| format!("{m:?}")),
            argnames = list(array_field(e, "proargnames"), |n| format!("{n:?}")),
            prosrc = str_field(e, "prosrc", ""),
            // The shared library a conversion or other C function lives in.
            // Empty for the internal functions, which is what the catalog
            // reports as NULL.
            probin = str_field(e, "probin", ""),
        );
        rows.push((oid, row));
    }
    rows.sort_by_key(|(oid, _)| *oid);
    for (_, row) in &rows {
        out.push_str(row);
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;

    const PROCS: &str = "[{ oid => '1242', proname => 'boolin', prorettype => 'bool', \
         proargtypes => 'cstring', provolatile => 'i' },\n\
          { oid => '1243', proname => 'boolout', prorettype => 'cstring', \
         proargtypes => 'bool' }]";

    fn fixture() -> (Vec<Entry>, SymbolTable) {
        let procs = parse_dat(PROCS);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        (procs, symbols)
    }

    #[test]
    fn emits_only_the_functions_something_points_at() {
        let (procs, symbols) = fixture();
        symbols.resolve_name(Proc, "boolin");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("proname: \"boolin\""));
        assert!(!emitted.contains("proname: \"boolout\""));
        // Argument and return types resolve even though `pg_type` referenced
        // this function first — that is the point of the two phases.
        assert!(emitted.contains("prorettype: 16"));
        assert!(emitted.contains("proargtypes: &[2275]"));
        assert!(emitted.contains("pronargs: 1"));
    }

    #[test]
    fn defaults_fill_the_columns_the_dat_omits() {
        let (procs, symbols) = fixture();
        symbols.resolve_signature(Proc, "boolout(bool)");
        let emitted = emit(&procs, &symbols);
        assert!(emitted.contains("prolang: 12")); // internal
        assert!(emitted.contains("procost: 1.0"));
        assert!(emitted.contains("prorows: 0.0")); // not set-returning
        assert!(emitted.contains("proisstrict: true"));
        assert!(emitted.contains("provolatile: \"i\""));
        assert!(emitted.contains("prokind: \"f\""));
    }

    /// Emit one entry, whatever it says, resolved against `bool`/`cstring`.
    fn emit_one(dat: &str) -> String {
        let procs = parse_dat(dat);
        let mut symbols = SymbolTable::default();
        symbols.define_name(Type, "bool", 16);
        symbols.define_name(Type, "cstring", 2275);
        define_symbols(&procs, &mut symbols);
        symbols.resolve_name(Proc, "f");
        emit(&procs, &symbols)
    }

    #[test]
    fn a_function_without_out_parameters_reports_the_three_columns_empty() {
        let (procs, symbols) = fixture();
        symbols.resolve_name(Proc, "boolin");
        let emitted = emit(&procs, &symbols);
        // Empty is the generated spelling of NULL, which is what PostgreSQL
        // stores for a function that declares neither OUT parameters nor
        // argument names.
        assert!(emitted.contains("proallargtypes: &[], proargmodes: &[], proargnames: &[]"));
        assert!(emitted.contains("probin: \"\""));
    }

    #[test]
    fn out_parameters_and_argument_names_are_emitted() {
        let emitted = emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargtypes => 'cstring', proallargtypes => '{cstring,bool}', \
             proargmodes => '{i,o}', proargnames => '{arg,found}', \
             probin => '$libdir/thing' }]",
        );
        // The type names resolve like any other reference; the modes and names
        // travel as written.
        assert!(emitted.contains("proallargtypes: &[2275, 16]"));
        assert!(emitted.contains("proargmodes: &[\"i\", \"o\"]"));
        assert!(emitted.contains("proargnames: &[\"arg\", \"found\"]"));
        assert!(emitted.contains("probin: \"$libdir/thing\""));
        // `pronargs` still counts the declared arguments, not the OUT ones.
        assert!(emitted.contains("pronargs: 1"));
    }

    #[test]
    #[should_panic(expected = "which codegen does not emit")]
    fn a_function_with_an_argument_default_is_refused() {
        emit_one(
            "[{ oid => '1', proname => 'f', prorettype => 'bool', \
             proargdefaults => '{false}' }]",
        );
    }
}
