//! `PG_TYPE_ROWS` codegen.

use std::collections::HashMap;
use std::fmt::Write as _;

use crate::dat::{Entry, bool_field, get, oid_field, str_field};
use crate::proc_ref;
use crate::symbols::SymbolKind::Type;
use crate::symbols::SymbolTable;

/// Phase one: every type name `pg_type.dat` defines, including the array types
/// it does not spell out. Array types have no `.dat` entry of their own — each
/// base type names its array's OID, and the array's name is the base's with a
/// leading underscore. `pg_proc` argument lists reference those names
/// (`_cstring`, `_text`), so the table has to carry them.
pub fn define_symbols(entries: &[Entry], symbols: &mut SymbolTable) {
    for e in entries {
        let Some(name) = get(e, "typname") else {
            continue;
        };
        symbols.define_name(Type, name, oid_field(e, "oid"));
        let array_oid = oid_field(e, "array_type_oid");
        if array_oid != 0 {
            symbols.define_name(Type, &format!("_{name}"), array_oid);
        }
    }
}

/// Emit `PG_TYPE_ROWS: &[PgTypeRow]` from `pg_type.dat`. Each base entry that
/// names an `array_type_oid` is followed by the row for its array type (see
/// [`array_row_for`]); the few array types the `.dat` spells out itself
/// (`_record`) come through as ordinary entries. Omitted columns fall back to
/// PostgreSQL's `pg_type` BKI defaults.
pub fn emit(entries: &[Entry], symbols: &SymbolTable) -> String {
    let regproc = |e: &Entry, key: &str| proc_ref(symbols, str_field(e, key, "-"));
    // Every OID and name the file itself claims, so a derived array row that
    // collides with a real type is a build failure rather than a duplicate row.
    // Both maps are filled before the loop: an entry that collides with a
    // derived row can appear anywhere in the file, above or below its element.
    //
    // Filled by an explicit loop rather than `collect`, which would drop a
    // duplicate silently. A `pg_type.dat` naming one type twice would then
    // reach `define_symbols`, where a name defined twice resolves to nothing —
    // and the symptom is a lie: `pg_cast` skips every cast touching the type,
    // and `pg_proc` reports the type as one `pg_type.dat` lacks.
    let mut used_oids: HashMap<u32, String> = HashMap::new();
    let mut used_names: HashMap<String, u32> = HashMap::new();
    for e in entries {
        let oid = oid_field(e, "oid");
        let typname = str_field(e, "typname", "").to_string();
        if let Some(other) = used_oids.insert(oid, typname.clone()) {
            panic!("pg_type OID {oid} is claimed by both {other:?} and {typname:?}");
        }
        if let Some(other) = used_names.insert(typname.clone(), oid) {
            panic!("pg_type name {typname:?} is claimed by both oid {other} and oid {oid}");
        }
    }
    let mut out = String::new();
    out.push_str("// @generated by crabgresql-bki from vendor/postgres/catalog/pg_type.dat\n");
    out.push_str("pub static PG_TYPE_ROWS: &[PgTypeRow] = &[\n");
    for e in entries {
        let oid = oid_field(e, "oid");
        let typname = str_field(e, "typname", "");
        assert!(
            oid != 0 && !typname.is_empty(),
            "pg_type entry missing oid/typname"
        );
        // typarray is usually given as `array_type_oid` (the array type is
        // derived); the entries whose array cannot be derived instead name it
        // outright, and that name resolves like any other reference.
        let array_oid = oid_field(e, "array_type_oid");
        let typarray = match array_oid {
            0 => get(e, "typarray")
                .and_then(|n| symbols.resolve_name(Type, n))
                .unwrap_or(0),
            autogen => autogen,
        };
        let base = TypeRow {
            oid,
            typname: typname.to_string(),
            typlen: resolve_typlen(str_field(e, "typlen", "0")),
            typbyval: bool_field(e, "typbyval", false),
            typtype: str_field(e, "typtype", "b"),
            typcategory: str_field(e, "typcategory", "X"),
            typispreferred: bool_field(e, "typispreferred", false),
            typdelim: str_field(e, "typdelim", ","),
            typsubscript: regproc(e, "typsubscript"),
            // typelem: element type by name (0 when the type is not an array/vector).
            typelem: get(e, "typelem")
                .and_then(|n| symbols.resolve_name(Type, n))
                .unwrap_or(0),
            typarray,
            typinput: regproc(e, "typinput"),
            typoutput: regproc(e, "typoutput"),
            typreceive: regproc(e, "typreceive"),
            typsend: regproc(e, "typsend"),
            typmodin: regproc(e, "typmodin"),
            typmodout: regproc(e, "typmodout"),
            typanalyze: regproc(e, "typanalyze"),
            typalign: resolve_typalign(str_field(e, "typalign", "i")),
            typstorage: str_field(e, "typstorage", "p"),
            typcollation: resolve_typcollation(e),
        };
        out.push_str(&base.emit());

        if array_oid == 0 {
            continue;
        }
        let array = array_row_for(&base, array_oid, symbols);
        if let Some(other) = used_oids.insert(array_oid, array.typname.clone()) {
            panic!(
                "array type OID {array_oid} for {typname:?} collides with existing type {other:?}"
            );
        }
        if let Some(other) = used_names.insert(array.typname.clone(), array_oid) {
            panic!(
                "array type name {:?} for {typname:?} collides with existing type oid {other}",
                array.typname
            );
        }
        out.push_str(&array.emit());
    }
    out.push_str("];\n");
    let _ = writeln!(out);
    out
}

/// One emitted `PgTypeRow` literal. Both the base rows read from `pg_type.dat`
/// and the array rows derived from them go through this, so the two can never
/// drift in column order or in the fields this build hardcodes.
struct TypeRow<'a> {
    oid: u32,
    typname: String,
    typlen: i16,
    typbyval: bool,
    typtype: &'a str,
    typcategory: &'a str,
    typispreferred: bool,
    typdelim: &'a str,
    typsubscript: String,
    typelem: u32,
    typarray: u32,
    typinput: String,
    typoutput: String,
    typreceive: String,
    typsend: String,
    typmodin: String,
    typmodout: String,
    typanalyze: String,
    typalign: &'a str,
    typstorage: &'a str,
    /// A Rust *expression* for the collation OID, not the OID itself: the
    /// generated file is `include!`d into the crate, so a named constant reads
    /// better than the bare number. Emitted with `{}`, unlike its string
    /// neighbours — `{:?}` here would quote it into a `u32` field.
    typcollation: &'a str,
}

impl TypeRow<'_> {
    fn emit(&self) -> String {
        let TypeRow {
            oid,
            typname,
            typlen,
            typbyval,
            typtype,
            typcategory,
            typispreferred,
            typdelim,
            typsubscript,
            typelem,
            typarray,
            typinput,
            typoutput,
            typreceive,
            typsend,
            typmodin,
            typmodout,
            typanalyze,
            typalign,
            typstorage,
            typcollation,
        } = self;
        format!(
            "    PgTypeRow {{ oid: {oid}, typname: {typname:?}, typnamespace: 11, \
typowner: crate::oids::BOOTSTRAP_ROLE_OID, typlen: {typlen}, typbyval: {typbyval}, \
typtype: {typtype:?}, \
typcategory: {typcategory:?}, typispreferred: {typispreferred}, typisdefined: true, \
typdelim: {typdelim:?}, typrelid: {typrelid}, typsubscript: {typsubscript}, \
typelem: {typelem}, typarray: {typarray}, \
typinput: {typinput}, typoutput: {typoutput}, typreceive: {typreceive}, \
typsend: {typsend}, typmodin: {typmodin}, typmodout: {typmodout}, \
typanalyze: {typanalyze}, typalign: {typalign:?}, typstorage: {typstorage:?}, \
typcollation: {typcollation} }},\n",
            // TODO: emit typrelid for the handful of catalog composite types,
            // which needs the pg_class OID of the relation `pg_type.dat` names
            // for them; this codegen resolves type and function names, never a
            // relation. 0 is the right answer for every other type.
            typrelid = 0,
        )
    }
}

/// The array type PostgreSQL serves for an entry carrying `array_type_oid`. A
/// varlena of the element type with the array I/O functions: `typname` gets the
/// conventional `_` prefix, `typcategory` is `A`, and storage is extended.
/// `typdelim` and `typcollation` are inherited (`box` separates with `;`, so
/// `_box` does too; `_text` sorts under the element's collation), but `typalign`
/// is *not* — it widens to `i` for everything narrower, since the array header
/// is int-aligned. The `regproc` columns are the array family's own, not the
/// element's: `array_in`/`array_out`/`array_recv`/`array_send`,
/// `array_subscript_handler` and `array_typanalyze`. Every value here is pinned
/// against a live `pg_type` by `array_rows_are_derived_from_their_element`.
fn array_row_for<'a>(base: &TypeRow<'a>, oid: u32, symbols: &SymbolTable) -> TypeRow<'a> {
    TypeRow {
        oid,
        typname: format!("_{}", base.typname),
        typlen: -1,
        typbyval: false,
        typtype: "b",
        typcategory: "A",
        typispreferred: false,
        typdelim: base.typdelim,
        typsubscript: proc_ref(symbols, "array_subscript_handler"),
        typelem: base.oid,
        // An array of arrays is not a type of its own here, as upstream.
        typarray: 0,
        typinput: proc_ref(symbols, "array_in"),
        typoutput: proc_ref(symbols, "array_out"),
        typreceive: proc_ref(symbols, "array_recv"),
        typsend: proc_ref(symbols, "array_send"),
        // An array takes no typmod and uses the array-wide statistics routine.
        typmodin: proc_ref(symbols, "-"),
        typmodout: proc_ref(symbols, "-"),
        typanalyze: proc_ref(symbols, "array_typanalyze"),
        typalign: if base.typalign == "d" { "d" } else { "i" },
        typstorage: "x",
        typcollation: base.typcollation,
    }
}

/// Symbolic `typlen` constants used in `pg_type.dat`, which PostgreSQL's own
/// catalog generator substitutes before the values reach `pg_type`. We fix the
/// 64-bit answers, matching the `server_version` we report.
fn resolve_typlen(s: &str) -> i16 {
    match s {
        "NAMEDATALEN" => 64,
        "SIZEOF_POINTER" => 8,
        other => other
            .parse()
            .unwrap_or_else(|_| panic!("unexpected typlen {other:?}")),
    }
}

/// `typalign`, likewise: `pg_type.dat` spells two entries' alignment as a
/// symbol, and PostgreSQL serves the substituted single character. On the
/// 64-bit target [`resolve_typlen`] already assumes, a pointer is 8 bytes and so
/// aligns like a double.
fn resolve_typalign(s: &str) -> &str {
    match s {
        "ALIGNOF_POINTER" => "d",
        // The whole vocabulary of the column, spelled out so a typo in a
        // re-vendored file fails the build instead of reaching `pg_type`.
        "c" | "s" | "i" | "d" => s,
        other => panic!("unexpected typalign {other:?}"),
    }
}

/// `typcollation` as `pg_type.dat` writes it: the *name* of the collation a
/// value of the type sorts under, or absent when the type is not collatable.
/// Only two names appear, and both have a constant in `crabgresql-types`.
fn resolve_typcollation(e: &Entry) -> &'static str {
    match get(e, "typcollation") {
        None => "0",
        Some("C") => "crabgresql_types::collation::C_COLLATION_OID",
        Some("default") => "crabgresql_types::collation::DEFAULT_COLLATION_OID",
        Some(other) => panic!("unexpected typcollation {other:?}"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dat::parse_dat;
    use crate::symbols::SymbolKind::Proc;
    use crate::symbols::SymbolTable;

    fn symbols_for(types: &[Entry]) -> SymbolTable {
        let mut symbols = SymbolTable::default();
        define_symbols(types, &mut symbols);
        for (name, oid) in [
            ("boolin", 1242u32),
            ("array_in", 750),
            ("array_out", 751),
            ("array_recv", 2400),
            ("array_send", 2401),
            ("array_subscript_handler", 1191),
            ("array_typanalyze", 1024),
        ] {
            symbols.define_name(Proc, name, oid);
        }
        symbols
    }

    #[test]
    fn an_array_row_follows_its_element() {
        let types = parse_dat(
            "[{ oid => '16', array_type_oid => '1000', typname => 'bool', typlen => '1', \
             typbyval => 't', typcategory => 'B', typinput => 'boolin', typalign => 'c' }]",
        );
        let emitted = emit(&types, &symbols_for(&types));
        let rows: Vec<&str> = emitted
            .lines()
            .filter(|l| l.contains("PgTypeRow {"))
            .collect();
        assert_eq!(rows.len(), 2);
        assert!(rows[0].contains("typname: \"bool\""));
        assert!(rows[0].contains("typarray: 1000"));
        // The array row is derived: element OID, array I/O, `i` alignment.
        assert!(rows[1].contains("typname: \"_bool\""));
        assert!(rows[1].contains("typelem: 16"));
        assert!(rows[1].contains("typinput: ProcRef { oid: 750, name: \"array_in\" }"));
        assert!(rows[1].contains("typalign: \"i\""));
    }

    #[test]
    fn an_unresolvable_regproc_emits_the_catalog_none() {
        let types = parse_dat("[{ oid => '16', typname => 'bool', typinput => 'boolin' }]");
        let emitted = emit(&types, &symbols_for(&types));
        assert!(emitted.contains("typoutput: ProcRef { oid: 0, name: \"-\" }"));
    }

    #[test]
    #[should_panic(expected = "is claimed by both oid")]
    fn two_entries_sharing_a_type_name_fail_the_build() {
        // Without this the name is merely poisoned in the symbol table, and
        // what the build reports instead is that `pg_type.dat` lacks the type.
        let types = parse_dat(
            "[{ oid => '16', typname => 'bool' },\n\
              { oid => '17', typname => 'bool' }]",
        );
        emit(&types, &symbols_for(&types));
    }

    #[test]
    #[should_panic(expected = "collides with existing type")]
    fn a_derived_array_colliding_with_a_real_type_fails_the_build() {
        let types = parse_dat(
            "[{ oid => '16', array_type_oid => '1000', typname => 'bool' },\n\
              { oid => '1000', typname => 'other' }]",
        );
        emit(&types, &symbols_for(&types));
    }
}
