[package]
name = "crabgresql-planner"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crabgresql-binder.workspace = true
crabgresql-storage-api.workspace = true
crabgresql-types.workspace = true

[dev-dependencies]
crabgresql-memory-storage.workspace = true
crabgresql-parser.workspace = true
