[package]
name = "crabgresql-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
pg-ryu = { workspace = true }
icu_collator = { workspace = true }
icu_locale_core = { workspace = true }
jiff = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
anyhow.workspace = true
