--
-- MATH
-- The radian trigonometric tier (sin/cos/tan/cot, asin/acos/atan/atan2), the
-- angle conversions pi()/degrees()/radians(), and gcd()/lcm() over int4, int8
-- and numeric. Output generated by running this file through psql -a -q
-- against PostgreSQL, then compared byte-for-byte.
--

-- extra_float_digits = 3 is the shortest-exact float8 output, so a last-bit
-- divergence in any of these shows up here rather than hiding behind rounding.
SET extra_float_digits = 3;

--
-- pi() and the angle conversions
--
SELECT pi();
SELECT degrees(1.0::float8) AS one_radian, radians(180.0::float8) AS half_turn;
SELECT degrees(0.0::float8) AS zero, radians(0.0::float8) AS zero_r,
       degrees(-1.0::float8) AS neg;
-- the conversions are total on the infinities; only the *result* can overflow
SELECT degrees('infinity'::float8), degrees('-infinity'::float8),
       radians('infinity'::float8);
SELECT degrees('nan'::float8), radians('nan'::float8);
SELECT degrees(1e308::float8);
SELECT radians(1e-323::float8);
-- a subnormal result is fine; only a flush to zero is an underflow
SELECT degrees(1e-310::float8), radians(1e-310::float8);

--
-- sin / cos / tan / cot: the platform's libm, with no exactness correction
--
SELECT sin(0.0::float8), cos(0.0::float8), tan(0.0::float8);
SELECT sin(1.0::float8), cos(1.0::float8), tan(1.0::float8), cot(1.0::float8);
SELECT sin(radians(30.0::float8)) AS sin30, cos(radians(60.0::float8)) AS cos60;
-- cot is 1/tan, so the denominator's signed zero picks the sign of the pole
SELECT cot(0.0::float8) AS pos_zero, cot('-0'::float8) AS neg_zero;
SELECT tan(pi()/2) AS near_pole;
-- NaN passes through; an infinite angle has no value and is an error
SELECT sin('nan'::float8), cos('nan'::float8), tan('nan'::float8),
       cot('nan'::float8);
SELECT sin('infinity'::float8);
SELECT cos('-infinity'::float8);
SELECT tan('infinity'::float8);
SELECT cot('infinity'::float8);

--
-- asin / acos / atan / atan2
--
SELECT asin(0.0::float8), asin(1.0::float8), asin(-1.0::float8);
SELECT acos(0.0::float8), acos(1.0::float8), acos(-1.0::float8);
SELECT asin(0.5::float8), acos(0.5::float8);
-- outside [-1, 1] — including the infinities — is a domain error
SELECT asin(1.5::float8);
SELECT acos(-1.5::float8);
SELECT asin('infinity'::float8);
SELECT acos('-infinity'::float8);
SELECT asin('nan'::float8), acos('nan'::float8);
-- atan and atan2 are total: an infinity is a limit, not an error
SELECT atan(0.0::float8), atan(1.0::float8), atan(-1.0::float8);
SELECT atan('infinity'::float8), atan('-infinity'::float8), atan('nan'::float8);
SELECT atan2(1.0::float8, 1.0::float8), atan2(-1.0::float8, 1.0::float8),
       atan2(0.0::float8, -1.0::float8);
SELECT atan2('infinity'::float8, 'infinity'::float8),
       atan2('infinity'::float8, 'nan'::float8),
       atan2(1.0::float8, 'infinity'::float8);
-- an integer argument reaches float8 through the usual implicit cast
SELECT sin(0), cos(0), atan2(1, 1);

--
-- gcd / lcm: integer overloads
--
SELECT gcd(6, 4), gcd(-6, 4), gcd(6, -4), gcd(-6, -4);
SELECT gcd(0, 0), gcd(0, -5), gcd(5, 0), gcd(1, 1);
SELECT lcm(6, 4), lcm(-4, 6), lcm(0, 5), lcm(5, 0), lcm(0, 0);
SELECT gcd(1071, 462), lcm(21, 6);
SELECT gcd(6::int8, 4::int8), pg_typeof(gcd(6::int8, 4::int8));
-- the overflow condition is a result the type cannot hold, so it depends on
-- the width: |int4 min| does not fit in int4, but it does fit in int8
SELECT gcd((-2147483648)::int4, 0::int4);
SELECT gcd(0::int4, (-2147483648)::int4);
SELECT gcd((-2147483648)::int4, (-2147483648)::int4);
SELECT gcd((-2147483648)::int4, 2::int4);
SELECT gcd((-2147483648)::int8, 0::int8);
SELECT gcd((-9223372036854775808)::int8, 0::int8);
-- a zero operand answers before anything is multiplied, so it never overflows
SELECT lcm((-2147483648)::int4, 0::int4);
SELECT lcm((-2147483648)::int4, 1::int4);
SELECT lcm(2147483647::int4, 2147483646::int4);
SELECT lcm(4611686018427387904::int8, 2::int8);

--
-- gcd / lcm: numeric
--
SELECT gcd(4.2::numeric, 2.8::numeric), lcm(4.2::numeric, 2.8::numeric);
SELECT gcd(1.5::numeric, 0.5::numeric), lcm(1.5::numeric, 0.5::numeric);
-- the display scale of both is max(scale(x), scale(y))
SELECT gcd(2.0::numeric, 4.000::numeric), lcm(2.0::numeric, 4.000::numeric);
SELECT gcd(0.30::numeric, 0.2::numeric), lcm(0.30::numeric, 0.2::numeric);
SELECT gcd(0::numeric, 0.00::numeric), lcm(0::numeric, 0.00::numeric);
SELECT gcd(-4.20::numeric, 0::numeric), lcm(3::numeric, 0.5::numeric);
SELECT gcd(1e10::numeric, 1e5::numeric);
-- unlike the integer overloads, a magnitude with no finite divisor is NaN
SELECT gcd('nan'::numeric, 1), lcm('nan'::numeric, 1);
SELECT gcd('infinity'::numeric, 1), lcm('infinity'::numeric, 2);
SELECT gcd(0::numeric, '-infinity'::numeric), lcm('nan'::numeric, 'infinity'::numeric);
-- wider than either integer type
SELECT gcd(12345678901234567890123::numeric, 123::numeric);
SELECT lcm(9999999999999999999999::numeric, 9999999999999999999998::numeric);
-- a numeric argument binds the numeric overload exactly; an integer one does not
SELECT pg_typeof(gcd(6, 4)), pg_typeof(gcd(6.0, 4.0)), pg_typeof(lcm(6, 4));

--
-- NULL is NULL throughout (every function here is strict)
--
SELECT sin(NULL::float8), degrees(NULL::float8), atan2(NULL::float8, 1.0::float8);
SELECT gcd(NULL::int4, 4), lcm(4.2::numeric, NULL::numeric);
