[package]
name = "crabgresql-binder"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
crabgresql-parser.workspace = true
crabgresql-pg-wire.workspace = true
crabgresql-storage-api.workspace = true
crabgresql-types.workspace = true

[dev-dependencies]
crabgresql-memory-storage.workspace = true
